### ISSUE TITLE
Possibility to group and sort the imports of a document

### ISSUE THREAD

**Issue by michaeljota** [buehler/typescript-hero#102]
I believe I saw a sorting function. 
I think that would be a great point to start the semantic order thing (#82).
## Update

A new configuration section to sorting:
- `typescriptHero.sort`  
  To define all the sorting options
  value type: `Object`
- `typescriptHero.sort.type`
  To define the sorting type
  value type: `string`. Possible values: `ascending` | `descending` | `semantic`
  _If none is giving, `ascending` would be default_
- `typscriptHero.sort.auto`
  To enable autosort after a `resolver` import have been made.
  value type: `boolean`
- `typescriptHero.sort.semantic`
  To define the semantic sort order
  value type: `string[]`. Possible values: `plains`, `globals`, `locals`.
  _If `sort.type` it's set to semantic, but `sort.semantic` it's not set, `ascending` would be used_
  _Any field that it's not set in the semantic order, have to be sorted at the end_
  _In any case, `ascending` should always be the prefer way to sorting_

Maybe some inspiration from here [(tslint) member-ordering](https://palantir.github.io/tslint/rules/member-ordering/)
## Original

Add new configurations to sorting:
- `typescriptHero.resolver.sort`  
  To define the sorting order  
  value type: `ascending` | `descending` | `semantic`
- `typescriptHero.resolver.autoSort`  
  To enable autosort after an `resolver` import have been made  
  value type: `boolean`

Add a configuration to the semantic sorting:
-  `typescriptHero.resolver.semanticSorting`  
  To define the semantic sorting order  
  value type: `string[]`

Posible enums values:
- `plains` are plains imports, ex:  
  `import 'uiframework/dist/uiframework.css';`
- `globals` are globals modules imports, ex:  
  `import { Component } from '@angular/core';`
- `locals` are locals class/modules imports, ex:  
  `import { AppComponent } from './app.component';`

It could event have something like: 
- `withPrefix: string[]` to sort all modules with that prefix.

``` json
// Example config file
...
"typescriptHero.resolver.sort": "semantic",
"typescriptHero.resolver.autoSort": true,
"typescriptHero.resolver.semanticSorting": [
  "plains",
  "globals",
  "withPrefix": [
    "@angular"
    "@ngrx"
  ],
  "locals"
]
```

UPDATE: I do realize that an array can't contain another array. I'll look about how should that be placed.

I still got couple of questions about this...
- If sorting order it's set to semantic, but no semantic sorting if giving,
  it should have a `default` semantic order? Or should it continue to sort alphabetically
- If the semantic sorting does not have all the properties defined, should it 
  place all the undefined properties at the bottom?

I started this as a comment in #82, but even if this is a way to solve it, this is mostly about the sorting functionality.

**Comment by buehler** [comment]
I do like this purposal. There has to be a way to do it with the configuration, since #80 is not gonna be possible. Comments are ignored by the typescript compiler. I built this extension on top of the typescript compiler to make use of the AST of a file. I do not want to parse the document with regex to search for comments. So this sorting feature has to be something like this. 

Very good idea.

I really like the definitions of the imports. If you have any ideas about the config, shoot right away.

**Comment by michaeljota** [comment]
@buehler I updated the original post. 

I see how `tslint` have rules to order internal members, maybe this can take some inspirations from there.

**Comment by buehler** [comment]
I got an idea for configuration:

```json
"typescriptHero.resolver.importSorting": [
    "KEY",
    /regex/,
    { identifier: "KEY", order: "asc" | "desc" },
    { identifier: /regex/, order: "asc" | "desc" }
]
```

the order would be like the ordering in the array. now possible keys are:
`modules` which are basically all imports from `node_modules`
`plains` as you purposed, are the side-effect only imports `import 'reflect-metadata';
`workspace` which are the files that are imported from the local workspace
`others` (which will be implicit at the end, if not defined) which identifiers the rest, that is not grouped anyhow.

now for `regex` one can choose a regex string (or should it be an array of regexes?) to match the import library name against.

if multiple matches are defined for an import, the first would do.

example:

```json
/angular/,
"local"
```

this would create two groups:
```typescript
import { Component } from '@angular/core';
import { Http } from '@angular/http';

import 'reflect-metadata';
import { Foobar } from './foo';
```

another example with "others" in the middle:
/http/,
"others",
"local"

this would create two groups:
```typescript
import { Url } from 'http';
import { Http } from '@angular/http';

import 'reflect-metadata
import { Component } from '@angular/core';

import { Foobar } from './foo';
```

This way, everything should be configurable. And the default would be:
"others" in alphabetical order.

**Comment by michaeljota** [comment]
I like your proposal. It's clear and intuitive. 👍 

BTW: You have a typo
workspace `which are the files that are imported from the local workspace` others` (which will be implicit at the end, if not defined) which identifiers the rest, that is not grouped anyhow.

I guess should be:
`workspace` which are the files that are imported from the local workspace
`others` (which will be implicit at the end, if not defined) which identifiers the rest, that is not grouped anyhow.

I'm looking forward to see this. Thanks you.

**Comment by buehler** [comment]
Thanks :-)

yea.. a purposal for the default could be:
```
"plains",
"modules",
"others"
```

all in normal alphabetical order
