### ISSUE TITLE
Feature: add all missing imports

### ISSUE THREAD

**Issue by MastroLindus** [buehler/typescript-hero#106]
It would be really convenient to have a way to quickly trigger a command that will add all missing imports from the file (for imports that have only one result available, obviously it cannot work automatically if you have two or more imports available for the same symbol).

**Comment by buehler** [comment]
Hey @MastroLindus 
Yes that is a good idea. I already had that, but thought it would be fair enough with the #11. 

If the lightbulb feature would add the missing imports, would that be enough?

Cheers

**Comment by MastroLindus** [comment]
Hi @buehler ,

Ideally I would like some kind of command that I can either assign a shortcut to or even better run everytime I save my code, I am not sure the lightbulb feature could provide that? (not really familiar with that feature)

**Comment by buehler** [comment]
The lightbulb feature does underline your symbol and says there is something missing. You can then ask the code action provider what to do. And I could provide the solution "import ...".

So this would then import the stuff you need.

The other thing could be a command. Maybe I'm gonna do that, we'll see.

What I definitly cannot do is run the command on every save. The extension does edit the file and when you save the document, it will be flagged dirty right away again. So it'll cause an infinite loop :-)

**Comment by lucasbasquerotto** [comment]
Hi @buehler 

Fisrt I would like to thank you for the great plugin, it saves me lots of time :)

If I understood correctly, the lightbulb would import only 1 symbol each time. I think it would be great if you could **import all non-imported symbols in the file at once** (giving that there is only 1 result found for that symbol).

Do you have something like this in mind?

Cheers

**Comment by buehler** [comment]
Hey @lucasbasquerotto 
I've implemented it in the PR #116 but I need to add it as a command :-)
