### ISSUE TITLE
Add implement interface functionality

### ISSUE THREAD

**Issue by michaeljota** [buehler/typescript-hero#114]
#### System information

- OS: any
- TypeScript Hero version: 0.9.0
- VSCode version: 1.6.1

#### Feature Implement interface

A lightbub that allows to implement the interface properties automatically.

#### Reason

Cause we as programmers are lazy and we don't want to setup the properties. xd

#### References

TypeStrong/atom-typescript#256

**Comment by buehler** [comment]
Hey @michaeljota 
Yep that's definitively on the plan :-)
I'm currently working on it @ #11

**Comment by michaeljota** [comment]
OMG! Thanks you! :D
