### ISSUE TITLE
Won't import, no errors

### ISSUE THREAD

**Issue by subvertallchris** [buehler/typescript-hero#117]
#### System information

- OS: Mac OS 10.11.6
- TypeScript Hero version: 0.9.0
- VSCode version: 1.7.1

#### Description

Import does not... import?

##### Steps to reproduce

Select an entry from the global list of available imports or use "Add import under cursor" option with a known valid importable... thing. No error, nothing happens.

I'm quite new to VS Code, so it's possible that I'm missing some "hey-n00b-you-forgot-to-do-this-thing" step, but, uhh... I dunno about that? Looking forward to any advice, this lack of import shortcuts is driving me nuts.

**Comment by subvertallchris** [comment]
Interestingly, it looks like it might be doing _something_, as it asks for clarification when it isn't sure which file to import or if it needs a variable for a default import. It just never shows up in my imports list.

**Comment by buehler** [comment]
Hey @subvertallchris 
Humm... interesting

I need to investigate that. Will come back to you as soon as I got my refactorings and code action provider coded :-)

**Comment by subvertallchris** [comment]
Cool, looking forward to your findings. Another possible clue: when I try to import something that is already listed, it tells me that the constant "was not found in the index or is already imported." If I had to guess, the problem is in whatever code is responsible for actually inserting the import statement on the page.

**Comment by buehler** [comment]
Well I hope the problem is solved with the new version, but maybe there is more investigation work to do :-)

**Comment by subvertallchris** [comment]
Success! Victory! All hail the new version! Thanks for the follow-up, I'm so excited to have this working.
