### ISSUE TITLE
Can't cancel actions

### ISSUE THREAD

**Issue by michaeljota** [buehler/typescript-hero#121]
#### System information

- OS: Windows 10 AU
- TypeScript Hero version: 0.10.0
- VSCode version: 1.7.1

#### Description

Can't cancel actions

##### Steps to reproduce

1. Show the command gui of typescript hero
2. Select add all missing imports or something
3. If it can't resolve all the imports, and ask for input the action can't be cancelled.

**Comment by buehler** [comment]
Whoops. :-/
That's not cool.

**Comment by buehler** [comment]
Well, quick question. There is a scenario where vscode keeps asking:
When there is another specifier with the same name

It will ask as long as the specifier is not unique (to prevent error code). Would it be more convenient to just let the user run into an error?

```typescript
import { Foobar } from 'something';
import { Foobar } from 'another';
```
The code above will produce an error.
VScode will ask as long as something like this is produced:

```typescript
import { Foobar } from 'something';
import { Foobar as Baz } from 'another';
```
The code above will not produce an error.

**Comment by buehler** [comment]
Or is it when multiple declarations for the same symbol are found?

**Comment by michaeljota** [comment]
> Or is it when multiple declarations for the same symbol are found?

The specific scenario was that indeed. I was trying to import something that was declared twice with the same symbol, and was unable to resolve witch one I wanted to use. 

I press `esc` hopping to cancel the action, but I did not. It keeps show and wouldn't go. As I said in #122, I close the VS Code instead.

**Comment by buehler** [comment]
Hmm I see... I'll investigate that matter ☝️

**Comment by buehler** [comment]
@michaeljota It should work right now. So I removed all the "require" (aka while loop) so you can cancel the action
