### ISSUE TITLE
Light bulb support for tsx files

### ISSUE THREAD

**Issue by megaboich** [buehler/typescript-hero#128]
#### System information

- OS: Windows 10
- TypeScript Hero version: 0.10.1
- VSCode version: 1.7.1

#### Description

Awesome extension, helped me a lot during my last huge code refactoring.
Very useful when you have moved bunch of files and then it is very boring to manually type all new imports.

While it worked flawlessly for .ts files I do not see any bulb for .tsx files.
If that is the issue please fix it.

##### Steps to reproduce

Go to .tsx file and remove all imports. Then put cursor on some red reference and try to get a light bulb action.

**Comment by buehler** [comment]
Hey @megaboich 
Seems like the registering of the code action provider missed tsx :-)
Will have a look into it
