### ISSUE TITLE
High load in extension host

### ISSUE THREAD

**Issue by jrieken** [buehler/typescript-hero#143]
We have identified[1] this extension as cause for high load in the [extension host](http://code.visualstudio.com/docs/extensions/our-approach#_stability-extension-isolation). That's the process *all* extensions share and doing computational expensive operations in there is unfair towards other extensions. We recommend to perform CPU-heavy operations like parsing, building indices, etc in a language service process which again communicates with the extension host. A good sample for that is [vscode-eslint](https://github.com/Microsoft/vscode-eslint).

[1] How do we know? The extension host must send a [ping](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/extensionHost.ts#L123) every 250ms to the main thread. If that doesn't happen 4 times in a row we send a telemetry event containing the ids of all active extensions. Those lists of ids we analyse to find extensions that occur over and over again.

**Comment by buehler** [comment]
Hey @jrieken 
Alright, thank you! I assume this load is occuring because of the filewatcher? 
I'll definitly have a look into it

**Comment by buehler** [comment]
Addition: do I get you right, you have a "server - part" in your extension,  that is loaded and communicates with the normal extension through this host process?

**Comment by jrieken** [comment]
re https://github.com/buehler/typescript-hero/issues/143#issuecomment-266199519 - File watching already happens in a separate process so I believe the problem is [here](https://github.com/buehler/typescript-hero/blob/master/src/caches/ResolveIndex.ts#L125). Imagine starting of a large project of 1000 files. You will find, load, parse, and post process all of them which is likely to max out the extension host process.

**Comment by jrieken** [comment]
re https://github.com/buehler/typescript-hero/issues/143#issuecomment-266301878 - Yes. That it is

**Comment by buehler** [comment]
@jrieken: I got a small question, is it possible to use service workers instead of the language-server?  Would that solve the high-load problem? (just wondering)

Cheers

**Comment by jrieken** [comment]
There are no service workers or web workers, the context you are in is nodejs. And yes, the language server protocol allows to send/receive any kind of message in addition to the well known messages

**Comment by buehler** [comment]
Hey @jrieken 
I got a question regarding the server part implementation. Is it possible to use `vscode` as a package in the server implementation?

i.e. can I do: `import { Range } from 'vscode';` and then `let foobar = new Range(/*...*/);`

Right now, when I try to do that, the server dies and tells me the module "vscode" is not found. Is it because it is linked via `npm link` or because the vscode context is not loaded?

Is there another possibility to use those packages? Since I can provide code actions and stuff, I should be able to instantiate them right?

Cheers
Chris

**Comment by jrieken** [comment]
Yeah, the `vscode` package is very special. We make it look like an npm module but in reality it is something very dynamic we get to you [hijacking](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts#L544) node's require...

Having said that, I know that @aeschli maintains a node module that contains most of the business objects like Range, Position et al

**Comment by buehler** [comment]
Alright, I'm going to have a look at that package, thanks for pointing that out!
This "problem" of the high load, triggered a major refactoring. In a good way.

By the way, I like the line where you hijack the node loader 😂

**Comment by aeschli** [comment]
The node module is called vscode-languageserver-types, it contains all the base type of the language server, including 'Range'

**Comment by buehler** [comment]
Hey @aeschli 
Thank you for pointing that out, I'll have a look at it.
