### ISSUE TITLE
Ignore certain folders for imports

### ISSUE THREAD

**Issue by yannbf** [buehler/typescript-hero#144]
#### Feature Ignore certain folders for imports

Title says it all 

#### Reason

First of all, I really like what has been done with this extension.
But there is one thing that I don't like. I'm using it with ionic 2 and there is always that .tmp folder in the middle of imports. I want to ignore that, therefore, making anything related to that temporary folder to not show in imports. I was trying to use "TypescriptHero.resolver.ignorePatterns": ".tmp/*" but I believe I got it wrong. Is there already something done for that?

**Comment by buehler** [comment]
actually, you just can write ".tmp" to ignore the folder. I just check for the names. This is a good feature request, to ignore patterns with glob style.

**Comment by buehler** [comment]
I'm closing this issue as a "non issue" since it is possible to ignore it, but I'll open another one for the glob feature.
