### ISSUE TITLE
Organise imports removes too much

### ISSUE THREAD

**Issue by nwolverson** [buehler/typescript-hero#149]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may event implement it and send a PR which would be very appreciated>

#### System information

- OS: Win7
- TypeScript Hero version: 0.11.0
- VSCode version: 1.8.0

#### Description

When editing a TSX file, organise imports command removes the `React` import which is required for JSX to work.

##### Steps to reproduce

1. Edit a TypeScript file containing some react code using JSX tags
2. Run organise imports command

Code no longer compiles due to lack of import.

**Comment by Ventajou** [comment]
I too have a disappearing `import` statement, in my project when using that feature. I have an `app.ts` file at the root of the project which exports a default variable called `app`. Most of my files have a line as such:

    import app from '../app';

and when I use the Organize feature, that one line disappears each time...

**Comment by cgatian** [comment]
It would be nice if you could specify a pattern for organization.

Personally, I like node specific modules first, followed by a line feed, and then all local application imports.

**Comment by sevaru** [comment]
Organize imports removes ListViewModel import for some reason.
I guess it's related to default exports/imports
```
//... other imports
import ListViewModel from './ListViewModel';

export default class ListView extends BaseView<ListViewModel> {}
```

**Comment by HimmetAvsar** [comment]
Got the same issue. When i use ctrl+alt+o some used imports are always removed. 

import ConfigService from "../modules/ConfigService";
Configservice exports default class.

**Comment by ctretyak** [comment]
+1

**Comment by ctretyak** [comment]
import Variables from "~/services/variables";
...

req.checkBody('password')
        .notEmpty()
        .isLength({ min: Variables.registration.password.minLength })

and after organize it remove always

**Comment by ChuckJonas** [comment]
this happens with default imports on reducers...
