### ISSUE TITLE
Enable setting to auto organize

### ISSUE THREAD

**Issue by thekalinga** [buehler/typescript-hero#150]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may event implement it and send a PR which would be very appreciated>

#### System information

- OS: Ubuntu 14.04
- TypeScript Hero version: 0.11.0
- VSCode version: 1.9.0-insider

#### Feature Auto organize

Instead of remembering to add shortcuts, it would be better for users to enable auto organize feature. 
Once enabled, the moment user deletes a reference to a class, the plugin can auto remove corresponding import aswell.

#### Reason

User dont need to remember a shortcut & use this shortcut on each file. Improves his productivity

**Comment by ngfk** [comment]
Personally I would like an option to organise on save, no need for realtime organization.

**Comment by buehler** [comment]
This would be a great idea. Problem is: when I organize the imports, the document is marked as "dirty". And when somebody (like myself) has the "auto-save-on-focus-lost" feature of vscode enabled, this would end up in an infinite loop.

Dunno what to do :-/

**Comment by RandomShaper** [comment]
This would also help in the case where an import automatically added doesn't respect the sorting (or is that a bug and should be reported aside?).

@buehler, I think organize imports could do its job "offline" and only change the actual document if a change has been actually needed.

An alternative would be to work in the document itself but reseting the dirty flag if it wasn't on before the organize, as long as no changes have been made. (As long as VS Code provided such an API; I know nothing about extension development.)

Just some raw ideas.

**Comment by ngfk** [comment]
@buehler with "auto-save-on-focus-lost" you mean setting "files.autoSave" to "onFocusChange", right?

**Comment by buehler** [comment]
@ngfk Yea exactly this setting :-)

Oh ok, I'll have a look at it then.. Thanks for the hints!

**Comment by garethflowers** [comment]
Would love to see something like this as well!

Our current workflow is to Organise, Add Missing then Save (i.e. <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>O</kbd> then <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> then <kbd>Ctrl</kbd>+<kbd>S</kbd>).

**Comment by zbarbuto** [comment]
Plugins like Prettier hook into the `editor.formatOnSave` - is there any way that TypeScript hero could do the same?

**Comment by wshaver** [comment]
I'm wanting to use Typescript Hero, but need this one to move off of the sort-imports plugin.
