### ISSUE TITLE
Preserve case of file during auto indent

### ISSUE THREAD

**Issue by johnfn** [buehler/typescript-hero#154]
First and foremost, thanks for the awesome extension, man! Auto-import saves me 5-10 headaches a day. 😉 

Anywho.

Believe it or not, require.js has a bug where it treats "myFile" and "myfile" as two separate imports. Crazy? Yes. Terrible? Yes. BUT, we deal with it! 😉 

It would be really nice if the auto imports from TypeScript Hero would preserve the casing of the file, rather than lowercasing them! Then I wouldn't run into this terrible require.js bug. 😛

**Comment by buehler** [comment]
Hey @johnfn 

Thanks for your words!

That's a pretty strange behaviour.. do you use namespaces in files? or does auto organize cause the lowerspace filenames?

Cheers

**Comment by johnfn** [comment]
My mistake - I think this was a bug in VSCode rather than your plugin!
