### ISSUE TITLE
Cannot open command GUI after new install

### ISSUE THREAD

**Issue by paustint** [buehler/typescript-hero#155]
#### System information

- OS: ODX Sierra 10.12.2 (16C67)
- TypeScript Hero version: 0.11.0
- VSCode version: 1.8.1

#### Description
I have tried to install this extension on two different OSX machines and have not successfully been able to open the command gui on either one, with the following error message being displayed when trying to open the GUI:

`Error: "Cannot convert undefined or null to object"`

##### Steps to reproduce

1. run command: showCmdGui showCmdGui

##### Screenshots
![extension__typescript_hero-command-palette](https://cloud.githubusercontent.com/assets/5461649/21578964/27cd7abc-cf53-11e6-806d-fd21d42ca94c.png)

![extension__typescript_hero-error-msg](https://cloud.githubusercontent.com/assets/5461649/21578960/107be4fc-cf53-11e6-83e0-05835b00eb71.png)

**Comment by buehler** [comment]
😱 

What codebase do you have? `ng-bootstrap` by any chance?

**Comment by buehler** [comment]
This could be related to #79

**Comment by buehler** [comment]
Update... this is related to #79. already saw this error
