### ISSUE TITLE
Feature Request: Weighted Ordering of potential imports

### ISSUE THREAD

**Issue by CoenraadS** [buehler/typescript-hero#159]
#### Weighted Ordering of potential imports

Currently potential imports are listed alphabetically
![image](https://cloud.githubusercontent.com/assets/5593825/21748999/4926f96c-d594-11e6-9b98-a01e3d3bae42.png)

I would like an option of change the weight of the results.

imo a better solution would be:

Priority 1 => Exact name matches

When there are multiple exact name matches:
Priority 2 => Most similar file paths

e.g. from my screenshot
Current file: `\src\client\js\lobby\lobbyEmitter.ts` => Importing `IClientToServer`

Exact results:
`\src\common\lobby\IClientToServer.ts` <= This one has most similar file path
`\src\common\login\IClientToServer.ts`

#### Reason

Less user actions to get the correct import. I just want to press enter, not type or search a list.

**Comment by buehler** [comment]
it's a good purposal but very hard to achieve ;-)

**Comment by CoenraadS** [comment]
I just realized I was using `resolve.addImport` instead of `resolve.addImportUnderCursor`, which works much better for what I wanted. 👍
