### ISSUE TITLE
QuickFix Lightbulb not showing

### ISSUE THREAD

**Issue by CoenraadS** [buehler/typescript-hero#160]
#### System information

- OS: `Windows 10`
- TypeScript Hero version: `0.12.0`
- VSCode version: `1.8.1`

#### Description

![image](https://cloud.githubusercontent.com/assets/5593825/21749311/a323ff8e-d59c-11e6-9cca-48187a6aacb4.png)

Here I have a class that implements an interface. When I click on either the Class or the Interface, no lightbulb shows in the margin and I cannot quickfix to implement the missing functions.

##### Steps to reproduce

1. Create a class that implements an interface

(Note: The quick fix does work for importing classes, so I know the extension is working)

**Comment by buehler** [comment]
@CoenraadS Is this still an issue?
