### ISSUE TITLE
Feature Request: Disable prompting for variable name

### ISSUE THREAD

**Issue by CoenraadS** [buehler/typescript-hero#161]
#### Disable prompting for variable 

It would be nice to have an option to disable the variable name prompt, and just use the default exported name.

#### Reason

Less user actions for people who only use the default names.

**Comment by thekalinga** [comment]
@CoenraadS Where does it ask for variable name?

**Comment by CoenraadS** [comment]
![image](https://cloud.githubusercontent.com/assets/5593825/22744727/7eb0a112-ee1e-11e6-9cc1-ea9ccc87f4b8.png)

**Comment by buehler** [comment]
Humm.. https://github.com/buehler/typescript-hero/blob/master/src/managers/ImportManager.ts#L382-L408

The structure of those "managers" will remain the same, even after the rewrite.
