### ISSUE TITLE
File names with preceeding underscore are not properly imported

### ISSUE THREAD

**Issue by bryanrideshark** [buehler/typescript-hero#163]
#### System information

- OS: Windows 8.1
- TypeScript Hero version: 0.12.0
- VSCode version: 1.8.1

#### Description

When a type definition exists in a file with an underscore in the name, TypeScript Hero does not inject the proper name:

````ts

// Assume Foo is defined in a file _index.ts

// What is happening: 
import {Foo} from '../../some/path/_';

// What should happen

import {Foo} from '../../some/path/_index';
````

##### Steps to reproduce

1. Create a type definition in a file which is prefixed with an underscore
2. Try to use TypeScript Hero to import that definition.

**Comment by buehler** [comment]
Hmm.. this error only happens to files that are named `index` (as I'm aware of)

Since index files are used to require folders. I think the check needs to see if the whole filename is just `index.ts`
