### ISSUE TITLE
[FEATURE REQUEST] Setting to disable tool-tip import suggestions from appearing while typing.

### ISSUE THREAD

**Issue by superamadeus** [buehler/typescript-hero#165]
#### Feature: Disable tool-tip from auto appearing while typing.

Enable the option to disable the tool tip from appearing while typing, and opt to only use it manually (via key-combination or clicking).

#### Reason

Sometimes I have no intention of importing something while typing, and the import suggestions come up, and I accidentally import something. One example I run into a lot is when defining inline templates in an Angular component.

**Comment by buehler** [comment]
Hey @superamadeus 
Actually, that would be a feature of vscode itself. As I'm aware of, you can disable the auto completion to open on typing.

Search for `suggest` in your settings: https://dl.dropboxusercontent.com/spa/agn3r6rkwi4rxn7/8mmqfjya.png

**Comment by superamadeus** [comment]
Thanks for the suggestion @buehler.

I didn't want to give up autocomplete all-around, so I found another option to help solve this problem: disable suggestion acceptance on "." (period key). 

If anyone else wishes to do this, add this to your keybindings:
```json
{
    "key": ".",
    "command": "-acceptSelectedSuggestion"
}
```

**Comment by buehler** [comment]
@superamadeus Thanks! I actually was looking for such a config. Did not know that is possible.

I checked, I cannot disable certain characters from accepting code completions, one has to do it with your configuration.
