### ISSUE TITLE
Remove unused imports without sorting

### ISSUE THREAD

**Issue by ilivit** [buehler/typescript-hero#166]
#### Feature: Organize imports only by removing unused ones

Enable an option for cleaning the imports without changing their order.

#### Reason

Sometimes I want to preserve the order of the imports for a reason (i.e. keep same kind of imports together). It would be great to have the ability to do that kind of organization.

**Comment by buehler** [comment]
Actually a good idea. :-) I'm currently refactoring the whole application due to #143 

But this is definitly a todo for after the rewrite.

**Comment by lnunno** [comment]
FYI this is in the setting:

`"typescriptHero.resolver.disableImportsSorting": true,`
