### ISSUE TITLE
Components generated using angular cli are not indexed unless changed manually

### ISSUE THREAD

**Issue by thekalinga** [buehler/typescript-hero#167]
#### System information

- OS: Ubuntu 14.04
- TypeScript Hero version: 0.12.0
- VSCode version: 

Version 1.10.0-insider
Commit 723b20093d2f525e84cdf94a52f7695d1d539273
Date 2017-02-03T07:02:18.522Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

#### Description

Components generated using angular cli `ng g c home` are not shown in the auto suggestions of other files, unless I manually edit HomeComponent.

After editing the component is available in the auto complete.

##### Steps to reproduce

1. Create a new project
2. Open `AppComponent`
2. Create a component using the command listed above `ng g c home`
3. Type `Home` and press `ctrl+space`
4. You should see `HomeComponent` as one of the suggestion, but you don't.

**Comment by buehler** [comment]
Thank you for the report! I'll have a look into that matter as soon as the rewrite of the extension is done :-)

**Comment by buehler** [comment]
Actually, this should be fixed with the newest releases
