### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by xblox** [buehler/typescript-hero#171]
Hi,
when using your extension, it will crash VSCode after a few minutes. I think its because of too many files or so. See [here](https://github.com/Microsoft/vscode/issues/13781) a related issue. 

I tried all sorts of things, latest VSCode/VSCode-Insiders , same for typescript versions. My folder has 813851 files.

**Comment by xblox** [comment]
ah, fully forgot the fix : after removing your extension: all good again

**Comment by buehler** [comment]
:-/
Hopefully the rewrite will fix those issues :)

**Comment by xblox** [comment]
yeah, no worry, wasnt using it
