### ISSUE TITLE
Does not index typescript modules

### ISSUE THREAD

**Issue by RPDeshaies** [buehler/typescript-hero#172]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may event implement it and send a PR which would be very appreciated>

#### System information

- OS: Windows 7
- TypeScript Hero version: 0.12.0
- VSCode version: 1.9.1

#### Description

Typescript Hero doesn't index module so it does not recognize when I export a module and try to use it else where

##### Steps to reproduce

1. export a module
```
export module MyModule {
    export const TOTO = 123
}
```
2. Try to use that module in another file
![image](https://cloud.githubusercontent.com/assets/6224111/22984248/c4b0461e-f372-11e6-8934-f19fe54a4240.png)

<for feature requests, please use the following template>

#### Feature <name>

<description>

#### Reason

<why it would be cool>

**Comment by arutkowski00** [comment]
I have exactly the same issue with exported namespace
