### ISSUE TITLE
Crash when debugging extension

### ISSUE THREAD

**Issue by CoenraadS** [buehler/typescript-hero#173]
#### System information

- OS: `Windows 10`
- TypeScript Hero version: `0.12`
- VSCode version: `1.9.1`

##### Steps to reproduce

1. Debug an extension
2. In the vscode window running under the debugger, open a project folder with an invalid project.json (e.g. `{a}`)
3. Observe crash in the parent vscode

__awaiter (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\caches\ResolveIndex.js:15)
findFiles (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\caches\ResolveIndex.js:227)
(anonymous function) (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\caches\ResolveIndex.js:110)
__awaiter (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\caches\ResolveIndex.js:19)
__awaiter (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\caches\ResolveIndex.js:15)
buildIndex (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\caches\ResolveIndex.js:102)
(anonymous function) (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\extensions\ResolveExtension.js:288)
__awaiter (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\extensions\ResolveExtension.js:19)
__awaiter (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\extensions\ResolveExtension.js:15)
refreshIndex (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\extensions\ResolveExtension.js:281)
initialize (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\extensions\ResolveExtension.js:112)
TypeScriptHero.constructor.context.extensions.forEach.o (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\TypeScriptHero.js:30)
TypeScriptHero (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\TypeScriptHero.js:30)
Resolver._createInstance (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\node_modules\inversify\lib\resolution\resolver.js:93)
Resolver._resolve (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\node_modules\inversify\lib\resolution\resolver.js:56)
Resolver.resolve (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\node_modules\inversify\lib\resolution\resolver.js:11)
(anonymous function) (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\node_modules\inversify\lib\kernel\kernel.js:226)
Kernel._resolve (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\node_modules\inversify\lib\kernel\kernel.js:225)
Kernel._planAndResolve (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\node_modules\inversify\lib\kernel\kernel.js:174)
Kernel._get (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\node_modules\inversify\lib\kernel\kernel.js:165)
Kernel.get (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\node_modules\inversify\lib\kernel\kernel.js:76)
activate (c:\Users\Coenraad\.vscode\extensions\rbbit.typescript-hero-0.12.0\out\src\extension.js:17)
t._callActivateOptional (extHostExtensionService.ts:333)
t._callActivate (extHostExtensionService.ts:325)
(anonymous function) (extHostExtensionService.ts:305)
m (winjs.base.raw.js:1170)
F.enter (winjs.base.raw.js:852)
n.Class.define._run (winjs.base.raw.js:1068)
n.Class.define._completed (winjs.base.raw.js:1036)
n.Class.derive.join.c (winjs.base.raw.js:1813)
n.Class.derive.join.i.forEach.J.then.o.(anonymous function) (winjs.base.raw.js:1838)
m (winjs.base.raw.js:1170)
F.enter (winjs.base.raw.js:852)
n.Class.define._run (winjs.base.raw.js:1068)
n.Class.define._completed (winjs.base.raw.js:1036)
n.Class.derive.join.c (winjs.base.raw.js:1813)
n.Class.derive.join.i.forEach.J.then.o.(anonymous function) (winjs.base.raw.js:1838)
m (winjs.base.raw.js:1170)
F.enter (winjs.base.raw.js:852)
n.Class.define._run (winjs.base.raw.js:1068)
n.Class.define._completed (winjs.base.raw.js:1036)
e.resolveOk (ipcRemoteCom.ts:97)
d (ipcRemoteCom.ts:207)
_combinedTickCallback (next_tick.js:67)
_tickCallback (next_tick.js:98)

**Comment by CoenraadS** [comment]
Making a new issue, I think I figured out the problem

**Comment by buehler** [comment]
Hopefully, this is resolved with the rewrite and v0.13
