### ISSUE TITLE
Anything like this for Visual Studio?

### ISSUE THREAD

**Issue by KirillMetrik** [buehler/typescript-hero#176]
Hello, thanks for the great tool but would like to ask whether there are any plans to do something similar for normal Visual Studio (not vscode)? In our project we still use Visual Studio because server part is on .Net.

**Comment by buehler** [comment]
Hey @KirillMetrik 
I'm sorry, my "good old VS" days are more or less over :-)

I don't have any plans to port this software to VS.
Nevertheless, we are planning a community for TypeScript IDE improvements, so maybe there will be a chance, somebody will port it.

Cheers
