### ISSUE TITLE
Duplicate folder path for Angular-specific imports

### ISSUE THREAD

**Issue by cvharris** [buehler/typescript-hero#178]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may event implement it and send a PR which would be very appreciated>

#### System information

- OS: Mac OSX El Capitain
- TypeScript Hero version: 0.12.0
- VSCode version: 1.10.2

#### Description

When I import Angular modules an extra/duplicate folder path is added to the import statement which is incorrect:

```typescript
import { Http } from '@angular/http/http' // <-- Extra/duplicate director added to path
import { Injectable } from '@angular/core' // <-- Autogenerated from `ng g service`

@Injectable()
export class CheckoutService {

  constructor(private http: Http) { } // <-- imported `Http`

}
```
This is a project built with Angular-Cli v1.0.0

##### Steps to reproduce

You can reproduce this among all the different ways to import: intellisense, light bulb, and command palette

**Comment by DuncanFaulkner** [comment]
I'm seeing the same thing 
Image showing the issue
![typescript-issue](https://cloud.githubusercontent.com/assets/1952116/24545575/8b9089ca-15ff-11e7-9313-bedfd2505557.png)

**Comment by johanroug** [comment]
I am also seeing the same problem. 
it writes this
`import { RendererType2 } from '@angular/core/core';`
but should write this
`import { RendererType2 } from '@angular/core';`

**Comment by buehler** [comment]
@johanroug Yea.. sadly the angular team somewhat changed their description (d.ts) format...

**Comment by XcyTheR101** [comment]
Also getting this. Any way to maybe change some settings file to cater for this until the problem is resolved?

**Comment by harisb2012** [comment]
Any updates to this? Also getting it.

**Comment by buehler** [comment]
@harisb2012 not yet.. was at the JSConf and need to do some other stuff first :-)
But anybody feel free to investigate the d.ts files to help solve the problem

**Comment by harisb2012** [comment]
@buehler - I can confirm that https://marketplace.visualstudio.com/items?itemName=pmneo.tsimporter works just fine. I'm pretty sure it is internal typescript hero bug.

**Comment by rajjejosefsson** [comment]
Same problem here

**Comment by mrcl** [comment]
@buehler, any hint where in the code to look for the issue?

**Comment by Rukenshia** [comment]
Just found this issue, this is very annoying. I really love this extension but this renders the whole import stuff useless for me.

**Comment by buehler** [comment]
My guess is, that the indexing process (so after the parsing) does export the stuff twice. I'm gonna have a look at it asap.
