### ISSUE TITLE
Make quotation marks being used configurable

### ISSUE THREAD

**Issue by Deilan** [buehler/typescript-hero#180]
Right now the extension automatically uses double quotation marks:
```typescript
import { Component, Input } from "@angular/core";
```

It would be great to allow usage of single quotation marks also:
```typescript
import { Component, Input } from '@angular/core';
```

**Comment by buehler** [comment]
Hey @Deilan 
This is configurable. What you're using is the auto-import feature of typescript 2.2 and the microsoft guys just add the double quotes.

There is an issue open over there to solve this. My extension does use the configured ones.

**Comment by Deilan** [comment]
@buehler Thanks for the response! Could you kindly tell me where I can learn more about option you are telling about?

**Comment by buehler** [comment]
@Deilan Of course: this would be the option `typescriptHero.resolver.stringQuoteStyle`
