### ISSUE TITLE
Detect imports that are used in tsx syntax -feature

### ISSUE THREAD

**Issue by ofirgeller** [buehler/typescript-hero#186]
When I remove unused imports the imports that are used as jsx elements are removed as well.

It would be better if they are not removed.

**Comment by buehler** [comment]
@ofirgeller 
Can you provide a code example? Never did jsx / tsx much myself

**Comment by ofirgeller** [comment]
Sure would be happy to. ill start with a short why and how it works.

JSX is a extention to JS meant to be pre-proccesed into js before running anywhere. in general it allows you to create xml/html elements in JS in a way that looks like XML and then gets converted into the equivalent JS code. usealy this means that you write less code and that the code you write is more WYSIWYG.

example of jsx syntax:

`var elm = <span>hello</span>;`

Can be converted into  (depending on the pre proccesser, here I assume it targets vanila js in the browser)

```
var elm = document.createElement('span');
elm.appendChild(document.createTextNode('hello'));
```
The tag name in jsx needs to be a name of a native element ('span') or a name of a function that is going to return an XML element. the second option is critical to the use of components.

If I have defined such a function and I am importing and using it the code might look like this

```
/// MyCustomElement.tsx
export function MyCustomElement() { 
 return <span>hello</span>
}
```


```
/// App.tsx
import MyCustomElement from './MyCustomElement';

var myElm = <MyCustomElement></MyCustomElement >;

document.appendChild(elm);
```

Now because I never use  'MyCustomElement' in regular js/ts code it appears to typescript-hero as if the import can be removed, but it is actually needed for the jsx/tsx part of the code.

**Comment by buehler** [comment]
This should work now.. (As I tested by hand)
