### ISSUE TITLE
Doesn't remove unused imports

### ISSUE THREAD

**Issue by gtzinos** [buehler/typescript-hero#205]
System information

OS: Windows 10
TypeScript Hero version: 0.13.1
VSCode version: 1.12.2
Description

When i try to sort my imports it doesn't remove any unused of them.

**Comment by buehler** [comment]
Right now, it seems to not remove imports that are used in comments.

**Comment by gtzinos** [comment]
It doesn't remove imports that not exists in the whole file.

**Comment by buehler** [comment]
@gtzinos Can you make an example?

**Comment by gtzinos** [comment]
Sure @buehler 

I am developing a component which it includes a module that it doesn't use, then i click on sort imports but it just sort them and doesn't remove it as expected.

import { Component } from '@angular/core';
import { Page } from '../../templates/page/page';
import { Websockets } from '../../../providers/api/websockets';

@Component({
    selector: 'login',
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.css']
})

export class LoginPage extends Page<LoginPage> {
    constructor() {
        super();
    }
}

**Comment by buehler** [comment]
Alright, so as I assume: `Websockets` should be removed.
I'll have a look at it :-)

**Comment by gtzinos** [comment]
Thank you for your support. You do a great job.
