### ISSUE TITLE
Triggering "Organize imports" ignores references encapsulated in namespace and throws them away.

### ISSUE THREAD

**Issue by Manusan42** [buehler/typescript-hero#214]
#### System information

- OS: Win10
- TypeScript Hero version: 1.0.0
- VSCode version: 1.13.1

#### Description

Triggering "Organize imports" ignores references encapsulated in namespace and throws them away.

##### Steps to reproduce

Considering the following code:
```ts
import * as http from 'http';
import * as https from 'https';

export namespace ServerManager {
  export interface ServerOptions {
    port?: number;
    server?: http.Server | https.Server;
  }
}

export interface ServerOptions {
  port?: number;
  server?: http.Server;
}
```

Now trigger "Organize imports" and the "https"-import is removed, because it is only referenced in the interface which is encapsulated in the exported namespace.

**Comment by buehler** [comment]
Will have a look at it asap !
