### ISSUE TITLE
Organize import does not work when the regex contains @ or |

### ISSUE THREAD

**Issue by P-H-F** [buehler/typescript-hero#218]
#### System information

- OS: Win7
- TypeScript Hero version: 1.0.0
- VSCode version: 1.13.1

#### Description

When I add an importGroup which either contains '@' or '|' (but is still a valid regex) the imports are not grouped.

###### Case 1: Scoped packages
1. Set setting `typescriptHero.resolver.importGroups` to `[ "/@angular/" ]`
2. Add angular import
3. Organize imports
4. No import group is created
(When I change the setting to `[ "/angular/" ]` the group is created correctly)

###### Case 2: Logical group of packages
1. Set setting `typescriptHero.resolver.importGroups` to `[ "/angular|rxjs/" ]`
2. Add angular & rxjs import
3. Organize imports
4. No import group is created

I'm actually not sure whether this use-case is supported, I was just assuming it'll work as it's stated that the library-name is matched against the regex, and it is a valid one.

**Comment by buehler** [comment]
Actually this is a bug then. This should be a supported use case.
