### ISSUE TITLE
don't reorganise my imports on "add import" + add import at cursor position

### ISSUE THREAD

**Issue by fxck** [buehler/typescript-hero#22]
When I add an import it currently reorganises all of my imports, which is quite annoying. What would be nice if it added the import at cursor position and didn't touch my other imports at all.

What do you think?

**Comment by buehler** [comment]
Why add the import at the cursor position? It may shouldn't organize the imports on add import action, but I'd add the import at the top of the document.

It is code design guide line (IMO) to have all imports at the start of the docs.

Or not?

**Comment by fxck** [comment]
That depends, I have my imports in certain order, 

- angular imports
- 3rd party imports 
- services 
- components 

Something along these lines. And when it puts it on the top, I usually have to move it to the correct place anyway, so I'd rather clicked on the place I wanted the import at and then did alt + ctrl + i.

**Comment by buehler** [comment]
Hmm

Alright.. currently I'm rewriting the index core to improve the speed drastically. But after that, I'm looking into it. I currently don't know if its cool for everyone to add the import at the cursor (like I use it myself, I just want to import the stuff and work where I'm at) 

Maybe that can be configurable?

Let's see when I'm done with the indexing core.

**Comment by fxck** [comment]
Yep that would be perfectly fine having it optional.

Thanks!

**Comment by buehler** [comment]
Closed by #28
The simple "add import" or "add import under the cursor" do not reorganize the imports.
If you run the command to organize, all imports are consolidated / sorted / filtered by usage.

**Comment by fxck** [comment]
Cool, you gonna release it anytime soon(no idea how that VSC marketplace work)?

**Comment by buehler** [comment]
Yea, I'm gonna do some testing on the master branch (with the help of @n00dl3) and if I'm certain, everything should work as expected, I'm gonna release it under v 0.6

**Comment by fxck** [comment]
@buehler how is it supposed to work? When I press the command ctrl + alt + shift + i nothing comes up..

**Comment by buehler** [comment]
When nothing comes up, the symbol is already imported. You only see a selector list, when there are multiple definitions that match the currently typed filter.

When you type `Foobar` and hit the combination, the import should be automatically inserted.

**Comment by buehler** [comment]
But there is actually the following unreleased feature: If you do not correctly type out the whole word, you'll see the list anyway. So this will be in the next release.

![vid](http://www.giphy.com/gifs/3o6ZtqrDgq2u52tURO)

**Comment by fxck** [comment]
Ok, that is a little confusing, do I have to know precise name of what I want to import beforehand then? Why doesn't it work the same way `ctrl+alt+i` does, so I could search for it? 

Also it's still doing some reorganisations.

This is what my imports look like before using it: 

```typescript
import { NgModule, ApplicationRef } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { HttpModule, Http } from '@angular/http';
import { RouterModule } from '@angular/router';

import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import { RouterStoreModule } from '@ngrx/router-store';
import { AUTH_PROVIDERS, AuthConfig, AuthHttp } from 'angular2-jwt';

// modules
import { SharedModule } from './shared/shared.module';

// services
import {
  Ng2Permission,
  PermGuard
} from './shared/services/permission.service';
import { ENV_PROVIDERS } from './environment';

// routes
import routes from './app.routes';

// actions
import actions from './shared/actions';

// reducers
import reducers from './shared/reducers';

// effects
import effects from './shared/effects';

// services
import services from './shared/services'

// component modules
import { MdIconModule } from '@angular2-material/icon';

import { UserModule } from './shared/components/user/user.module';
import { AppBarModule } from './shared/components/app-bar/app-bar.module';

// components
import { AppComponent } from './app.component';
import { BurgerComponent } from './shared/components/burger/burger.component';
import { AppMenuComponent } from './shared/components/app-menu/app-menu.component';
import { SearchContainer } from './shared/containers/search/search.container';
import {
  NotificationCounterComponent
} from './shared/components/notification-counter/notification-counter.component';

// material2 components
import { MdSidenavModule } from '@angular2-material/sidenav';
import { MdMenuModule } from '@angular2-material/menu';
import { MdRadioModule } from '@angular2-material/radio';
import { MdTooltipModule } from '@angular2-material/tooltip';
```

..now I want to add `DatePlateComponent` so I put my cursor right after this part

```typescript
import {
  NotificationCounterComponent
} from './shared/components/notification-counter/notification-counter.component';
```

so I write `DatePlateComponent`, press the command and this is the result 

```typescript
import { Ng2Permission, PermGuard } from './shared/services/permission.service';
import services from './shared/services';
import { NotificationCounterComponent } from './shared/components/notification-counter/notification-counter.component';
import { DatePlateComponent } from './shared/components/date-plate/date-plate.component';
import { ApplicationRef, NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { Http, HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';

import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import { RouterStoreModule } from '@ngrx/router-store';
import { AUTH_PROVIDERS, AuthConfig, AuthHttp } from 'angular2-jwt';

// modules
import { SharedModule } from './shared/shared.module';

// services
import {
  Ng2Permission,
  PermGuard
} from './shared/services/permission.service';
import { ENV_PROVIDERS } from './environment';

// routes
import routes from './app.routes';

// actions
import actions from './shared/actions';

// reducers
import reducers from './shared/reducers';

// effects
import effects from './shared/effects';

// services
import services from './shared/services'

// component modules
import { MdIconModule } from '@angular2-material/icon';

import { UserModule } from './shared/components/user/user.module';
import { AppBarModule } from './shared/components/app-bar/app-bar.module';

// components
import { AppComponent } from './app.component';
import { BurgerComponent } from './shared/components/burger/burger.component';
import { AppMenuComponent } from './shared/components/app-menu/app-menu.component';
import { SearchContainer } from './shared/containers/search/search.container';
import {
  NotificationCounterComponent
} from './shared/components/notification-counter/notification-counter.component';
DatePlateComponent

// material2 components
import { MdSidenavModule } from '@angular2-material/sidenav';
import { MdMenuModule } from '@angular2-material/menu';
import { MdRadioModule } from '@angular2-material/radio';
import { MdTooltipModule } from '@angular2-material/tooltip';
```

here's the diff https://gist.github.com/fxck/3de2562469c0cd1a0a87e317a00e18cc/revisions?diff=unified

**Comment by buehler** [comment]
Oh.. I misunderstood you. "Import under the cursor" means, you actually import the symbol that is right under the cursor.

I'll make another ticket for that.

**Comment by buehler** [comment]
@fxck Could you check the text of the new ticket and complement the rest if needed?
