### ISSUE TITLE
Duplicate Imports

### ISSUE THREAD

**Issue by subvertallchris** [buehler/typescript-hero#226]
#### System information

- OS: Mac 10.11.6
- TypeScript Hero version: 1.0.0 + 1.1.0
- VSCode version: 1.13.1

#### Description

Adding a missing import duplicates existing imports in my file.

##### Steps to reproduce

1. Import a missing constant using keyboard shortcut to import under cursor, click on the option to import the missing constant, or click to attempt to add all if possible.

This _might_ have coincided from switching from awesome-typescript-loader back to ts-loader. I'll have to check on that but wanted to mention it in case it rings a bell with anyone.

**Comment by abdulkareemnalband** [comment]
I also have same issue so i reverted back to 0.13.2
here is vsix file if anybody needs it 
[typescripthero.0.13.2.vsix.zip](https://github.com/buehler/typescript-hero/files/1090332/typescripthero.0.13.2.vsix.zip)

**Comment by buehler** [comment]
ref: #175

**Comment by dskopa-softdev** [comment]
I have the same issue: when I add an import for a missing name, it duplicates the rest of import statements:

![Duplicate imports example](http://i.imgur.com/yr0oWon.gif)

TypescriptHero v 1.1.0

it's a fresh empty app created using `ng new`

**Comment by startswithaj** [comment]
Experiencing the same thing

**Comment by jmitchell89** [comment]
I also have this issue very annoying. 👎

**Comment by buehler** [comment]
Sadly, even I experience those bugs sometimes.. but I need some time to fix them. Which is a scarce resource right now.

**Comment by swissmanu** [comment]
@buehler can you point in some direction? maybe i find some time to look into.

**Comment by buehler** [comment]
My guess is, that the parsing of the pathes on are not the same. The method that implements all missing imports is found @ https://github.com/buehler/typescript-hero/blob/master/src/extension/extensions/ImportResolveExtension.ts#L307-L330
So when the import resolve extension wants to find the missing imports, it actually get's no matches for the existing ones

**Comment by acidduckling** [comment]
This only seems to happen if you do not sort the imports first - if you sort the imports with the default key binding (ctrl + alt + o) then the imports do not duplicate. At least that seems to be the case from what I experience!

**Comment by subvertallchris** [comment]
+1 here, sorting first prevents duplication. It also removes my `import * as React from 'react'`, which is equally annoying, but hopefully it helps troubleshooting.

**Comment by motiejunas** [comment]
same here after last release

**Comment by bryanrideshark** [comment]
Is there any way to just turn this off entirely? The tool is unusable now...

**Comment by buehler** [comment]
Uhm, yea I guess you should be able to disable the grouping feature by setting the settings:
`typescriptHero.resolver.importGroups` to `[]`

Then it should use the "remaining" group in asc mode. So you only have one import group which does not duplicate the imports (or should.)

**Comment by buehler** [comment]
heureka. @swissmanu & the others :-) I think I found the bug.
