### ISSUE TITLE
feature: ES2015 default import (and named import) syntax

### ISSUE THREAD

**Issue by wycats** [buehler/typescript-hero#227]
#### System information

- OS: Windows
- TypeScript Hero version: 1.1.0
- VSCode version: 1.13.1

#### Description

If I have an import with mixed default and named imports:

```ts
import DynamicHTMLContent, { DynamicTrustedHTMLContent } from './content/html';
```

And I organize imports, I get:

```ts
import { DynamicTrustedHTMLContent } from './content/html';
```

**Comment by buehler** [comment]
oh.. actually that's a total new syntax 😄 
When you use the following syntax it should work:
`import { default as DynamicHTMLContent, DynamicTrustedHTMLContent } from './content/html';`

Did not know that there are other ways to do this. I think my parser does not recognize the syntax.

**Comment by wycats** [comment]
@buehler which parser are you using? Certainly TS supports it. fwiw this syntax was included in ES2015.

**Comment by buehler** [comment]
I use the typescript compiler to create an AST. but this ast reads like hell, so I made my own strategy. It's possible that those things are not up to date. I need to implement that :)

**Comment by BruceHem** [comment]
haha, this happens to me too.
