### ISSUE TITLE
Interaction with VSCode 1.14.0 bug

### ISSUE THREAD

**Issue by MickeySegal** [buehler/typescript-hero#242]
#### System information

- OS: <Windows 10>
- TypeScript Hero version: <1.1.0>
- VSCode version: <1.14.0>

#### Description

TypeScript Hero seems to be running afoul of a bug in VSCode 1.14.0

##### Steps to reproduce

Discussed in https://github.com/Microsoft/vscode/issues/30486

**Comment by jrieken** [comment]
Nah, this is an issue in VS Code. Nothing to change in this extension. We have fix and are making sure to get it out asap.

**Comment by buehler** [comment]
@MickeySegal Thanks for the report
@jrieken  Thanks!
I also experienced very high cpu loads and I was wondering if my code was so drastically wrong.

I'm trying to improve the code in that manner for the sake of such changes.

Thank you guys!

**Comment by MickeySegal** [comment]
For those of us who are not familiar with the process for releasing a new version, please let us know if you release a workaround for general users faster than the VSCode fix that solves this at the other end.

Thanks for getting on this issue so promptly.

**Comment by buehler** [comment]
@MickeySegal I just published the hotfix. It's now released on the marketplace. So all you guys can update the extension now.

I use semantic releasing for this project (as of today) to publish any merges that are made into the master branch.

**Comment by MickeySegal** [comment]
The new version of TypeScript Hero installs with no difficulty.
