### ISSUE TITLE
import symbol exported via "export * from..."

### ISSUE THREAD

**Issue by n00dl3** [buehler/typescript-hero#25]
I'm working on an angular 2 application and if I import NgModule which is declared in @angular/core/src/metadata and re-exported in @angular/core/index.d.ts, the one imported is "@angular/core/src/metadata" and cause some major problems :
I don't know what kind of dark magic is really happening here, but it kinda import the source file instead of a compiled js and the program crashes at runtime...

**Comment by buehler** [comment]
During the creation of the symbol list, all "export ..." in a file are actually processed. So if an index.d.ts has an `export * from ...` those declarations are imported from the other name.

I have to investigate that behaviour. Actually, I never tested the plugin with angular 2, but I'll definitely have a look into that. I just need some time to do it ;-)

**Comment by n00dl3** [comment]
Just to be more precise :
> it kinda import the source file instead of a compiled js and the program crashes at runtime...

I'm talking about my angular app, not vscode nor the plugin...

**Comment by n00dl3** [comment]
OK, I think I found something:
[in file ResolveItemFactory.ts](https://github.com/buehler/typescript-hero/blob/master/src/factories/ResolveItemFactory.ts#L57-L60) :
The plugin only act on declarations but not on exported members.
I think it should actually change the library name of re-exported members recursively...

**Comment by n00dl3** [comment]
[I was f***ing right !](https://github.com/n00dl3/typescript-hero/blob/dev/src/factories/ResolveItemFactory.ts#L58-L73)

**Comment by buehler** [comment]
:-) good catch.

Since I'm rewriting this logic anyway, I can merge this and will keep it in mind for my new core logic.

**Comment by n00dl3** [comment]
ok, I'll make a PR.

**Comment by n00dl3** [comment]
Should be fixed by https://github.com/buehler/typescript-hero/commit/3de7214e47c245be5a3d4386f6d6fbaed552ac62
