### ISSUE TITLE
Request: Code outline position option (left/right)

### ISSUE THREAD

**Issue by caseyduquettesc** [buehler/typescript-hero#251]
#### Feature Code outline position

Add an option to place the code outline in a pane on the right hand side (like the minimap) because I like my list of files :)

#### Reason

I find myself resizing the panes often depending on if I want to look at the symbols in the code versus look at the files in the project. I'd rather have both lists, full height of the window because both are valuable to have.

**Comment by buehler** [comment]
Hey @caseyduquettesc 
As of now, this is not possible since the vscode extension api does not provide this feature.
Maybe on a later date ;-)

**Comment by caseyduquettesc** [comment]
Ah bummer, thanks for the feedback!
