### ISSUE TITLE
ignoreImportsForOrganize does not behave as expected

### ISSUE THREAD

**Issue by will093** [buehler/typescript-hero#258]
#### System information

- OS: Windows 10
- TypeScript Hero version: 1.3.0
- VSCode version: 1.13.1

#### Description

ignoreImportsForOrganize setting does not behave as expected.

##### Steps to reproduce

1. Add import:

`import {} from '@types/googlemaps';`

2. In the settings.json, ignore this import on organise:

`"typescriptHero.resolver.ignoreImportsForOrganize":["@types/googlemaps"]`

3. Reorganise imports (Ctrl-alt-o), import now becomes:

`import undefined from '@types/googlemaps';`

**Comment by buehler** [comment]
Actually, the `ignoreImports` does behave as expected, since the import is not removed 😉 
BUT: the `undefined` part is definitly a bug.

**Comment by buehler** [comment]
Actually, if you just want to import the types for the sake of it, you could use `import '@types/googlemaps';` But I don't know if there's any means to this.

I generally use that for reflect-metadata for example.

**Comment by will093** [comment]
@buehler Ahh you are right in that the bug is with the organise imports operation rather than `ignoreImportsForOrganize`. 

So in my specific use case I am using google maps in my Angular CLI project - my understanding is that the typescript compiler should find everything in `node_modules/@types` automatically - however it seems in the case of google maps there is some issue:

https://stackoverflow.com/questions/36064697/how-to-install-typescript-typings-for-google-maps

As suggested by the top solution, I am trying to use `import {} from '@types/googlemaps';`.

`import '@types/googlemaps';` does not work - it produces an error as `'@types/googlemaps'` contains a typescript namespace rather than a typescript module.
