### ISSUE TITLE
Incorrect resolution for Angular types

### ISSUE THREAD

**Issue by timosaikkonen** [buehler/typescript-hero#268]
#### System information

- OS: macOS Sierra 10.12.6
- TypeScript Hero version: 1.4.0
- VSCode version: 1.15.1
- Angular version: 4.1.3

#### Description

TS Hero seems to resolve a couple of Angular types incorrectly. This was less of a problem in 1.3.0 where I could manually correct the import and still use Organize Imports. Starting from 1.4.0 Organize Imports removes the imports that I've manually fixed. I imagine that's because organize imports now goes through the same type resolution as "add import" and removes the ones that don't match its resolution.

The expected behavior would be to import types like `SimpleChanges` and `ChangeDetectorRef` from `@angular/core`. Instead, it's resolving to `@angular/core/src/metadata/lifecycle_hooks`. I tried to use `ignorePatterns` to ignore `@angular/core/src` but it didn't seem to work.

##### Steps to reproduce

![image](https://user-images.githubusercontent.com/1052676/29396304-b08bad92-8349-11e7-869c-dd2e42018663.png)

**Comment by buehler** [comment]
This actually should be fixed with the new typescript features
