### ISSUE TITLE
Add import includes all types from node modules (insiders edition)

### ISSUE THREAD

**Issue by kdomagoj** [buehler/typescript-hero#269]
When I use "Add import" option to import lib , it lists all available types form node_modules 
even when ignorePatterns is enabled.

Settings part:

"typescriptHero.resolver.ignorePatterns": [
    "aws-sdk",
    "dist",
    "node_modules",
    "tslint"
    ]

**Comment by kdomagoj** [comment]
Can be solved with:

"files.exclude": {
         "node_modules" : true
  }

**Comment by buehler** [comment]
Actually this should be solved with #275
