### ISSUE TITLE
Organize import removes imports if they are used in property assignment

### ISSUE THREAD

**Issue by n00dl3** [buehler/typescript-hero#27]
(Still with angular 2.) I have a "routing table" that tells the app which class should be instanciated for the corresponding route, if I run the "organize imports" command in that file, it removes all my imports. These references should be taken in account by the plugin while organizing imports.

**Before:**

```typescript
import {AppointmentResolve} from "../../commons/dao/appointments/appointment-resolve.service";
import {PreparationResolve} from "../../commons/dao/preparation/preparation-resolve.service";
import {AmbianceComponent} from "./ambiance/ambiance.component";
import {DomainsComponent} from "./domains/domains.component";
import {InfoComponent} from "./info/info.component";
import {PrepIntroComponent} from "./intro/intro.component";
import {PreparationComponent} from "./preparation.component";
import {PresenceComponent} from "./presence/presence.component";
import {ShowcaseComponent} from "./showcase/showcase.component";
import {VisitsComponent} from "./visits/visits.component";
import {YellowPagesComponent} from "./yellowpages/yellowpages.component";
import {RouterModule, Routes} from "@angular/router";

const PreparationRoutes: Routes = [
  {
    path: "appointments/:id/preparation",
    component: PreparationComponent,
    resolve: {
      appointment: AppointmentResolve,
      preparation: PreparationResolve
    },
    children: [
      { path: "", component: PrepIntroComponent },
      { path: "info", component: InfoComponent },
      { path: "yellowpages", component: YellowPagesComponent },
      { path: "showcase", component: ShowcaseComponent },
      { path: "presence", component: PresenceComponent },
      { path: "visits", component: VisitsComponent },
      { path: "domains", component: DomainsComponent },
      { path: "ambiance", component: AmbianceComponent }
    ]
  }
];

export const PreparationRouting = RouterModule.forChild(PreparationRoutes);
```

**After :**

```typescript
import {RouterModule, Routes} from "@angular/router";

const PreparationRoutes: Routes = [
  {
    path: "appointments/:id/preparation",
    component: PreparationComponent,
    resolve: {
      appointment: AppointmentResolve,
      preparation: PreparationResolve
    },
    children: [
      { path: "", component: PrepIntroComponent },
      { path: "info", component: InfoComponent },
      { path: "yellowpages", component: YellowPagesComponent },
      { path: "showcase", component: ShowcaseComponent },
      { path: "presence", component: PresenceComponent },
      { path: "visits", component: VisitsComponent },
      { path: "domains", component: DomainsComponent },
      { path: "ambiance", component: AmbianceComponent }
    ]
  }
];

export const PreparationRouting = RouterModule.forChild(PreparationRoutes);
```

**Comment by n00dl3** [comment]
It comes from TsResolveFileParser.ts [at line 28](https://github.com/buehler/typescript-hero/blob/master/src/parser/TsResolveFileParser.ts#L28). 
why is `SyntaxKind.PropertyAssignment` disallowed for parent ?

**Comment by buehler** [comment]
I did not test it with angular, there were some PropertyAssignments where it should not be allowed. Well it seems that this PropertyAssignment is allowed after all. Well its 0.x version, so I assume there are many usecases that are not handled as well. It's kind of mindblowing with all the varieties that `.d.ts` files come by.

I had some major progress this evening with my rewrite, so I'll add that to the "investigation" list.

When I'm done with the rewriting, would you mind to test the branch on your local installation?

Cheers

**Comment by n00dl3** [comment]
I'd be glad to help, of course. I know it's a 0.x version and even if some use-cases are not handled I found this plugin was (one of) the most effective out there :wink: .

**Comment by buehler** [comment]
It should be fixed by #28
@n00dl3 would you mind to try it out (it's merged into the master)

I also remapped the "add import under the cursor" command to `ctrl+alt+shift+i`

Thanks for any suggestions ;-)
Cheers

**Comment by n00dl3** [comment]
It seems there are still some problem with organize imports.
(Fun fact: )I tested this in the plugin source (`src/parser/TsResourceParser.ts`).
It removes `injectable` and `Logger` from the list of imports.

**Comment by buehler** [comment]
well... booooh! 😄 
I'll open another ticket for that

**Comment by n00dl3** [comment]
I also tested in other files of the project and it removes several imports : `@decorators()` calls and interface "Y" in `class X implements Y{}`.
there are also more random behaviours in other files (`src/models/TsExports.ts`, for example).

However, the plugin seems to be a good example of real-life project for testing use-cases.

**Comment by buehler** [comment]
What about the vanishing import in an angular project?

**Comment by n00dl3** [comment]
No problem for property assignment in my routing table anymore.
