### ISSUE TITLE
resolve.add*Import* does not honor resolver.stringQuoteStyle 

### ISSUE THREAD

**Issue by supdegrave** [buehler/typescript-hero#270]
#### System information

- OS: MacOS Sierra
- TypeScript Hero version: 1.4.0
- VSCode version: 1.15.1

#### Description

Using any of the "add import" functionality encloses the import name / path in double-quotes, despite the default setting of `resolver.stringQuoteStyle="'"`. 

##### Steps to reproduce

1. Create an Angular CLI project and `npm install`
2. Add a reference to an angular Library, without importing
3. Use TypeScript Hero functionality to add the correct import statement

##### Actual behavior

No matter the `resolver.stringQuoteStyle` value, the import will be added wrapped in double-quotes. 

##### Expected behavior

Import quote style should honor the `resolver.stringQuoteStyle` value.

**Comment by buehler** [comment]
Hey @supdegrave 
Do you use the function provided by typescript hero or by typescript itself? They added the same "feature" but didn't make it configurable.

**Comment by supdegrave** [comment]
I've gone back to verify, and it appears that TS Hero is honoring stringQuoteStyle. 

It wasn't clear to me that the lightbulb is populated from different sources. The option that adds quotes is not from TS Hero, so I suspect you're right that it's the VSCode built-in option. 

Thanks for the reply.
