### ISSUE TITLE
Plugin started using so much CPU that Mac OS creates kernel_task for CPU not to overheat

### ISSUE THREAD

**Issue by idchlife** [buehler/typescript-hero#271]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: Mac OS 10.12.5
- TypeScript Hero version: 1.4.0
- VSCode version: 1.15.1

#### Description

Several days ago TypeScript Hero started doing something that
a) makes code helper use 200% of cpu (2 helpers which uses 100% of cpu each)
b) mac os creates kernel_task process so CPU wont overheat, it uses about 600% of cpu (I have 8 cores)

I checked many things in my system to discover that exactly this plugin does something that creates this condition.

I will gladly give more information for you to try to understand, what's going on.
Hero is the best TS plugin at the moment for TypeScript imports, it's really hard to work without it.
Thanks!

##### Steps to reproduce

1. Have same versions
2. Open 2 windows with ts node projects

<for feature requests, please use the following template>

#### Feature <name>

<description>

#### Reason

<why it would be cool>

**Comment by buehler** [comment]
Oh my 😨 
I'm gonna have a look at it, I will get back to you if I need more info!

Thank you!

**Comment by buehler** [comment]
Hey @idchlife 
Is this still an issue?

**Comment by idchlife** [comment]
Hi @buehler ! Actually it is not! Thanks 😉

**Comment by realappie** [comment]
I have a strange feeling this issue is still occuring.

**Comment by idchlife** [comment]
@realappie it really can be the very tricky types somewhere, really big project or something not so connected to typescript-hero. We're all looking for sasquatch for now I guess

**Comment by buehler** [comment]
Sadly, we are :-/

**Comment by realappie** [comment]
@idchlife I stand corrected, this issue was caused by [import-cost](https://github.com/wix/import-cost/issues/47)

**Comment by idchlife** [comment]
@realappie oh, I disabled this extension after using it for 2 hours back at the day. It was all fun and games until my project with 3 files began killing my laptop.

After that there were still issues. But yes, problem can be also with other extensions

**Comment by realappie** [comment]
@idchlife I disabled it too, not because of its performance. But because `auto-import` is integrated in vscode.

**Comment by shahata** [comment]
Issue is fixed in import-cost version 2.6.2, sorry for the trouble...
