### ISSUE TITLE
command 'typescriptHero.resolve.organizeImports' not found

### ISSUE THREAD

**Issue by distante** [buehler/typescript-hero#273]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: macOS Sierra 10.12.6
- TypeScript Hero version: 1.4.0
- VSCode version: 1.15.1 

#### Description

When I call `TS Hero : Organize Imports` VSCode says it can not find `typescriptHero.resolve.organizeImports`

##### Steps to reproduce

1. Open Project
2. cmd + shift + p
3. Organize Imports

![screen shot 2017-08-31 at 07 57 02](https://user-images.githubusercontent.com/5490201/29908667-c4446a2a-8e22-11e7-936c-7c0a5f8e9811.png)

**Comment by buehler** [comment]
hmm this seems as the extension is not loaded correctly..

**Comment by buehler** [comment]
You need to open at least 1 typescript file for the extension to load.

can you try to uninstall / install it?

**Comment by distante** [comment]
You were right. No idea what happened because it was working correctly. Maybe it was become corrupted when VS Code updated.

**Comment by muziekklas** [comment]
Since the latest update of code all my collegues have this issue. WE have the following versions:
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:55:03.538Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by chanlito** [comment]
I'm on version 1.19.3 and having this issue too.

**Comment by nschindl** [comment]
Same here:

Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:36:43.673Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

**Comment by buehler** [comment]
Well I'm getting it too.. but when I test it locally (prod and dev build) it works. It seems that they screwed something up with the activation events. The extension isnt event activated anymore :-/

**Comment by chanlito** [comment]
@buehler thanks for quick response, hmm it's kinda annoying to organize it manually, I'm used to cool extensions 😄

**Comment by buehler** [comment]
I found the error.. I'm just an idiot :-D
Bugfix is on the way.

**Comment by buehler** [comment]
I used `fs-extra` in the rewrite... and forgot to install it into package.json 😓

**Comment by muziekklas** [comment]
Got an ETA for release? Thanks for the quick response :)

**Comment by chanlito** [comment]
@muziekklas It's now working. 👍

**Comment by buehler** [comment]
🙇

**Comment by buehler** [comment]
It's released by now.. maybe you need to restart vscode or search for the extension to trigger auto update

**Comment by muziekklas** [comment]
Whoa danke dir!!
Ill test it monday morning. Your tool is really a Hero :)

**Comment by muziekklas** [comment]
@buehler We still got the issue: command 'typescriptHero.resolve.organizeImports' not found. We all reinstalled the tool manually. Does code maybe cache the plugins somehow?

**Comment by buehler** [comment]
Actually it shouldn't. You can check in `~/.vscode/extensions`. There should be only one extension by now.

BUT: the name of the command changed. it's not `typescriptHero.resolve.organizeImports` it's `typescriptHero.imports.organize` now. With the refactoring I needed to organize some things

**Comment by muziekklas** [comment]
Jup Indeed, the rename was the issue :) Danke fuer die schnelle Antwort!
