### ISSUE TITLE
[Question] How to provide importGroups settings?

### ISSUE THREAD

**Issue by gerleim** [buehler/typescript-hero#278]
(Updated: Had to write @ _space_ angular, without the space, the markdown messes with the imports.)

(Thanks for the extension, useful. And sorry for the lame question, I never configured an extension so far...)

## 1. How can I specify setting for importGroups?
I tried to add
    "typescriptHero.importGroups": [
      "Modules",
      "Workspace",
      "Plains",
    ]
to launch.json; did not work.

### Original:
import { OnDestroy } from '@ angular/core';
import { ActivatedRoute } from '@ angular/router';

import { FormControl, FormGroupDirective, NgForm } from '@ angular/forms';
import { HttpResponse } from '@ angular/common/http';

import { Subscription } from 'rxjs/Subscription';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/startWith';
import 'rxjs/add/operator/map';

import { ListsModel, FilteredListsModel, FormInfoModel } from '../../model';
import { Utils } from '../../utils';

### Default sort:
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/startWith';

import { HttpResponse } from '@ angular/common/http';
import { OnDestroy } from '@ angular/core';
import { FormControl, FormGroupDirective, NgForm } from '@ angular/forms';
import { ActivatedRoute } from '@ angular/router';
import { Subscription } from 'rxjs/Subscription';

import { FilteredListsModel, FormInfoModel, ListsModel } from '../../model';
import { Utils } from '../../utils';

### Desired A:
Angular first, rxjs (3party packages) second, project imports third.

import { HttpResponse } from '@ angular/common/http';
import { OnDestroy } from '@ angular/core';
import { FormControl, FormGroupDirective, NgForm } from '@ angular/forms';
import { ActivatedRoute } from '@ angular/router';

import { Subscription } from 'rxjs/Subscription';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/startWith';

import { FilteredListsModel, FormInfoModel, ListsModel } from '../../model';
import { Utils } from '../../utils';

### Desired B:
Order in a way where "@angular/core" comes before "@angular/common/http", because it is one level up. (Also, for my eyes "core" should come before anything not core).

import { OnDestroy } from '@ angular/core';
import { HttpResponse } from '@ angular/common/http';
import { FormControl, FormGroupDirective, NgForm } from '@ angular/forms';
import { ActivatedRoute } from '@ angular/router';

**Comment by buehler** [comment]
Hey @gerleim 

To answer your question 1: you need to put the settings into a `settings.json` file. The `launch.json` file won't do any good for this matter ;-)

You can use vscode to configure those things, just go to the user preferences, there you can switch between user config and workspace config.

It looks like you are using `basePath` or something right? Because I've never saw an import from empty (i.e. `import ... from ""`) and with base pathes I got some bugs around.

The rest should actually be configurable, you could have the setting:

```json
"typescriptHero.resolver.importGroups": [
    "/@angular/",
   "/rxjs/",
   "Modules",
    "Workspace"
]
```

**Comment by gerleim** [comment]
Hmm, if I press edit comment, I see content between the apostrophes.
Is this some markdown trick?

**Comment by buehler** [comment]
yea markdown does render stuff between apostrophes as "code blocks"

**Comment by gerleim** [comment]
I think the issue is this with the markdown:

"Typing an @ symbol, followed by a username, will notify that person to come and view the comment. This is called an “@mention”, because you’re mentioning the individual. You can also @mention teams within an organization."

How to add at sign? Not working with \@.

**Comment by gerleim** [comment]
I am unable to properly add code, I tried html codes, escapes, nothing works. I'm surprised with git markdown. (How to enter '@ angular/core' properly, not turning into '@angular/core'?)

But anyway, your answer was perfect, I was able to configure, so I close this Q.
