### ISSUE TITLE
Sorting cannot be disabled

### ISSUE THREAD

**Issue by augustas1** [buehler/typescript-hero#281]
After import group have appeared (typescriptHero.resolver.importGroups) seems that sorting cannot be disabled now. 'typescriptHero.resolver.disableImportsSorting' has no action.

**Comment by tills13** [comment]
Also, this should _not_ be enabled by default.

**Comment by stefan-schweiger** [comment]
@buehler I've narrowed the error down to this line:

https://github.com/buehler/typescript-hero/blob/5050d0cd34a3b24756b21f51c1a79f48aff65b5b/src/extension/managers/ImportManager.ts#L365-L368

This groups all imports by their respective ImportGroup and therefore discards any previous sorting.

A possible workaround would be something like this:

```TS
let imports;

if (this.config.resolver.disableImportSorting) {
    imports = this.imports
        .map(imp => ImportManager.generator.generate(imp as any))
        .join('\n');
} else {
    imports = this.importGroups
        .map(group => ImportManager.generator.generate(group as any))
        .filter(Boolean)
        .join('\n');
}
```

But for obvious reasons import grouping won't work anymore (I guess that wouldn't be expected anyways), and existing blank lines will get lost (this is a bummer and I'm not sure how to fix this).

What are your thoughts on this?
