### ISSUE TITLE
stringQuoteStyle ignored for import sorting

### ISSUE THREAD

**Issue by wshaver** [buehler/typescript-hero#303]
#### System information

- OS:  Windows 10
- TypeScript Hero version: 1.5.0
- VSCode version: 1.16.1

#### Description
I'm using double quotes:
 "typescriptHero.resolver.stringQuoteStyle": "\""

This quote style works when 

However, when Organizing imports, either using organizeOnSave or the menu:
![image](https://user-images.githubusercontent.com/786554/30718052-91830300-9ed3-11e7-8931-5b7ff2029814.png)

The quotes will always use single quotes. :( I've tried setting the double quotes setting in both my workspace and the individual project file. 

In looking at the unit tests (I couldn't get them to run at all, or I'd have tried to write a failing one) it looks like there's no testing around the quoting style. Something like this...
```

// ImportProxy.test.js
describe('toImport()', () => {
...

  it('should generate a double quoted TsNamedImport', () => {
const options: TypescriptGenerationOptions = {
            eol: ';',
            multiLineWrapThreshold: 120,
            multiLineTrailingComma: false,
            stringQuoteStyle: `"`,
            spaceBraces: true,
            tabSize: 4,
        };

           generator = new TypescriptCodeGenerator(options);

            proxy.addSpecifier('bar');
            proxy.addSpecifier('baz');
            generator.generate(proxy).should.equal(`import { bar, baz } from "foo";`);
        });
});
```

**Comment by wrager** [comment]
+1 for this bug. It seems that it comes with 1.5.0. The downgrading to 1.4.2 helped me.
