### ISSUE TITLE
Multi-imports being removed (due to organizeOnSave)

### ISSUE THREAD

**Issue by pedro-mass** [buehler/typescript-hero#305]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: macOS Sierra version 10.12.6
- TypeScript Hero version: 1.5.0
- VSCode version: 1.16.1

#### Description

<what is going wrong>
organizeOnSave is removing my default import on a multi-import statement.

##### Steps to reproduce

1. Have the editor format on save in settings
`
"editor.formatOnSave": true,
`
2. Importing React is a great example
```javascript
import React, { Component } from 'react';
```
3. Save the file, and notice the import change to
```javascript
import { Component } from 'react';
```

This causes big issues, b/c now I have to pay attention and import twice for the same module.
The fix I'm using is turning off `organizeOnSave`
`
"typescriptHero.resolver.organizeOnSave": false,
`
That way I don't have to change my correct way of writing imports.

**Comment by buehler** [comment]
Related to #227 
When you use the "older" syntax, it works

**Comment by pedro-mass** [comment]
So this is no longer an issue with the new syntax?

**Comment by buehler** [comment]
Not in the develop branch :-)
