### ISSUE TITLE
Feature: Toggle remove import behavior

### ISSUE THREAD

**Issue by yofreke** [buehler/typescript-hero#306]
#### Feature: Toggle remove import behavior

Organize imports is removing unused imports, I do not want this behavior on every project.

Can we add a boolean config value `typescriptHero.resolver.organize.remove`?

#### Reason

On older projects, some imports are left around even though the code is not used.  Would be nice to make use of "organize imports" on projects like this.

**Comment by didacrios** [comment]
You can use `ignoreImportsForOrganize` setting

**Comment by yofreke** [comment]
Would something like `ignoreImportsForOrganize": [ "/.*?/" ]` ignore everything?

**Comment by buehler** [comment]
Uhm by now it's not a regex.. but I'll take it into account :-)

**Comment by Meligy** [comment]
This feature is useful because while organize is mostly a non destructive feature, remove can be destructive.

And it makes things a bit future proof for issues like #301.

**Comment by buehler** [comment]
This was implemented with: https://github.com/buehler/typescript-hero/pull/315

**Comment by Meligy** [comment]
Yup, works as expected. Thanks Christoph :)

**Comment by buehler** [comment]
You're welcome :-) but actually the credit goes to @danieloprado
