### ISSUE TITLE
Organize import <ctrl>+<alt>+O removes imported functions

### ISSUE THREAD

**Issue by abdulkareemnalband** [buehler/typescript-hero#311]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: Windows 10
- TypeScript Hero version: 1.5.0
- VSCode version: ^4 bit 1.16.1

#### Description

On Organize Import function definitions are removed from import list

##### Steps to reproduce

1. import function from another file
2. Use that function in imported file
3. Issue Organize import command `<ctrl>+<alt>+O`
4. Function definitions are removed from import list

**Comment by buehler** [comment]
Could you make an example? This usages are complicated calculations and there are many cases where it works ;-)

**Comment by shobhitg** [comment]
I am facing this issue as well in one of my files.

But unfortunately, I can't create a simple enough example, since `<ctrl>+<alt>+O` works most of the times.

**Comment by danieloprado** [comment]
Same

**Comment by Meligy** [comment]
Can we please have a new release including this?
Thanks a lot!

**Comment by shobhitg** [comment]
Is there a debug mode in the extension so that collect logs and help with details. THis issue reproduces every now and then.

#315 is just a bandaid. I would like the imports to work correctly and remove unused stuff correctly too.

**Comment by buehler** [comment]
@shobhitg Yes it definitly is a bandaid. That's why the issue isn't closed.

To debug, you could set the verbosity to `All` and for this particular matter, use the parser (https://github.com/buehler/node-typescript-parser) standalone to parse your source and see if the identifiers are listed in "Usages" of the parsed resource.

The items are removed from the imports when they are not recognized as "used"

**Comment by shobhitg** [comment]
@buehler Thanks for pointers.

I was able to get the parser output for my impacted file.

First let look at the issue in my case.

This is before Organize:
![before ts hero organize](https://user-images.githubusercontent.com/440151/31747285-bd123510-b420-11e7-86c5-9cd62860a461.png)

And this is after Organize:
![after ts hero organize](https://user-images.githubusercontent.com/440151/31747288-c0eb0914-b420-11e7-8bd6-1319af720140.png)

The following is the parser output ([view in json editor online](http://jsoneditoronline.org/?id=017adc76b61d22ca6e2234e062bf43f5)):
```
{
  "filePath": "inline.tsx",
  "rootPath": "/",
  "start": 1,
  "end": 4701,
  "imports": [
    {
      "libraryName": "../../../../exdto",
      "start": 1,
      "end": 82,
      "specifiers": [
        {
          "specifier": "AggregateDataResponseEx"
        },
        {
          "specifier": "AggregateResponseEx"
        }
      ]
    },
    {
      "libraryName": "../../../shared/api/dto",
      "start": 83,
      "end": 248,
      "specifiers": [
        {
          "specifier": "AggregateDataResponse"
        },
        {
          "specifier": "HostNode"
        },
        {
          "specifier": "IpPool"
        },
        {
          "specifier": "LogicalSwitch"
        },
        {
          "specifier": "RelatedData"
        },
        {
          "specifier": "TransportZone"
        },
        {
          "specifier": "UplinkHostSwitchProfile"
        }
      ]
    },
    {
      "libraryName": "../../../shared/utils/array-rep",
      "start": 249,
      "end": 308,
      "specifiers": [
        {
          "specifier": "ArrayRep"
        }
      ]
    },
    {
      "libraryName": "../../../shared/api/payload",
      "start": 309,
      "end": 423,
      "specifiers": [
        {
          "specifier": "GetAggregateDataPayload"
        },
        {
          "specifier": "ListNodeCapabilitiesPayload"
        },
        {
          "specifier": "SearchPayload"
        }
      ]
    },
    {
      "libraryName": "../actions/workflow-fabric-actions",
      "start": 424,
      "end": 786,
      "specifiers": [
        {
          "specifier": "POPULATE_COUNTS"
        },
        {
          "specifier": "POPULATE_EDGES_ONLY_SEARCH"
        },
        {
          "specifier": "POPULATE_HOST_CLUSTERS_ONLY_SEARCH"
        },
        {
          "specifier": "POPULATE_HOSTS_ONLY_SEARCH"
        },
        {
          "specifier": "POPULATE_IPPOOLS_SEARCH"
        },
        {
          "specifier": "POPULATE_LIST_NODE_CAPABILITIES"
        },
        {
          "specifier": "POPULATE_OVERLAY_TRANSPORT_ZONES_SEARCH"
        },
        {
          "specifier": "POPULATE_UPLINK_HOST_SWITCH_PROFILES_SEARCH"
        },
        {
          "specifier": "POPULATE_VLAN_TRANSPORT_ZONES_SEARCH"
        }
      ]
    },
    {
      "libraryName": "../state/workflow-state",
      "start": 787,
      "end": 927,
      "specifiers": [
        {
          "specifier": "FabricCountState"
        },
        {
          "specifier": "WorkflowsFabricDataState"
        },
        {
          "specifier": "WorkflowsFabricState"
        },
        {
          "specifier": "WorkflowsFabricUIState"
        }
      ]
    }
  ],
  "exports": [],
  "declarations": [
    {
      "name": "fabricUiStateReducer",
      "isExported": true,
      "type": "WorkflowsFabricUIState",
      "start": 929,
      "end": 4701,
      "parameters": [
        {
          "name": "state",
          "type": "WorkflowsFabricUIState",
          "start": 966,
          "end": 995
        },
        {
          "name": "action",
          "start": 997,
          "end": 1003
        }
      ],
      "variables": [
        {
          "name": "payload",
          "isConst": true,
          "isExported": false,
          "type": "FabricCountState",
          "start": 1088,
          "end": 4701
        }
      ]
    }
  ],
  "resources": [],
  "usages": [
    "state",
    "WorkflowsFabricUIState",
    "action",
    "POPULATE_COUNTS",
    "payload",
    "FabricCountState",
    "",
    "ListNodeCapabilitiesPayload",
    "WorkflowsFabricDataState",
    "SearchPayload",
    "HostNode",
    "Object",
    "GetAggregateDataPayload",
    "AggregateResponseEx",
    "UplinkHostSwitchProfile",
    "IpPool",
    "uiState"
  ]
}
```

To me it seems that parser is doing its job fairly good.

Hope this information helps in the root cause.

**Comment by shobhitg** [comment]
@buehler Can you please indicate how do I `set the verbosity to _All_` ?

**Comment by buehler** [comment]
Ofc: open the settings in vscode and set `typescriptHero.verbosity` to `All`

**Comment by shobhitg** [comment]
@buehler 

So I debugged my code through Typescript-Parser.

I think I found the issue.

In https://github.com/buehler/node-typescript-parser/blob/develop/src/TypescriptParser.ts#L55

There needs to be a way to specify the ScriptKind to whatever filetype we are parsing.

It should be:
```
    import {
        ScriptKind
    } from 'typescript';

    public async parseSource(source: string, scriptKind: ScriptKind): Promise<File> {
        return await this.parseTypescript(createSourceFile('inline.tsx', source, ScriptTarget.ES2015, true, scriptKind), '/');
    }
```

And TypeScript Hero needs to pass `ScriptKind.TS` in `parseSource`.

If you think this analysis is correct, please go ahead and fix the issue.

**Comment by shobhitg** [comment]
Here is my suggested fix in a pull request:
https://github.com/buehler/node-typescript-parser/pull/33
