### ISSUE TITLE
Sort by Import Name

### ISSUE THREAD

**Issue by Amerzel** [buehler/typescript-hero#316]
#### Feature - Add option to sort by import name

For some strange reason my team likes to sort their imports by first import name rather than path. I love some of the features TypeScript Hero provides and it would be great if it could also sort my imports as well.

#### Example

```
import { ReallyBad, Bad } from '../../bad";
import { Good, PrettyGood } from '../good';
import { Amazing } from 'amazing-packages';
```
would be sorted like:
```
import { Amazing } from 'amazing-packages';
import { Bad, ReallyBad } from '../../bad";
import { Good, PrettyGood } from '../good';
```

**Comment by buehler** [comment]
Not a planned feature right now ;-) but feel free to contribute

Relates #308

**Comment by Amerzel** [comment]
Thanks!

**Comment by buehler** [comment]
You need to thank @tdd :-) He's the typescript hero of that feature!

**Comment by yuriykuzin** [comment]
@buehler @tdd 
Looks like this great and absolutely necessary in our team feature is broken currently.
In my vscode settings I have: 
```
"typescriptHero.imports.organizeSortsByFirstSpecifier": true,
```
But imports are not sorted by first entity name:
```
import { PortalModule } from '@angular/cdk/portal';
import { ScrollDispatchModule } from '@angular/cdk/scrolling';
import { CommonModule } from '@angular/common';
```

VSCode is latest: 1.23.1 (1.23.1)
TypeScriptHero: 2.3.2

**Comment by tdd** [comment]
Hey @yuriykuzin!

I'm delighted to hear you liked that feature. God knows I loved it too (having written it).  I noticed it breaking a while ago, though, and alerted @buehler to it.

Unfortunately when VSCode started implementing their own import organizer and auto-import features, I believe @buehler thought this would make TSH's feature redundant—or at the very least more difficult to manage w/o conflict. So the plan was more to shave some yak and refocus on other aspects of the extension.

I now need to find time to contribute that same option to VSCode directly, I guess 😐

**Comment by yuriykuzin** [comment]
Thanks @tdd for your reply!

It's a pity though, as TSH is a great extension with all these group settings, but is not helpful in our case.

**Comment by tdd** [comment]
It is great, I wish it could collaborate with Code's behaviour better.

On Thu, Jun 7, 2018, at 11:59, Yuriy Kuzin wrote:
> Thanks @tdd[1] for your reply!


> It's a pity though, as TSH is a great extension with all these group
> settings, but is not helpful in our case.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
--
Christophe Porteneuve
tdd@tddsworld.com

Links:

  1. https://github.com/tdd
  2. https://github.com/buehler/typescript-hero/issues/316#issuecomment-395364632

**Comment by ShadabFaiz** [comment]
Is this issue of   `typescriptHero.imports.organizeSortsByFirstSpecifier: false`, not working fixed?
