### ISSUE TITLE
Imports being incorrectly removed by organizer

### ISSUE THREAD

**Issue by gianmarcotoso** [buehler/typescript-hero#318]
#### System information

- OS: Mac OSX High Sierra
- TypeScript Hero version: 1.5.0
- VSCode version: 1.17.0

#### Description

In a situation like

```
import Stuff from './Stuff'

export default Stuff
```

the import is being incorrectly removed

##### Steps to reproduce

1. Write a new `index.js` file containing the lines 
```
import Stuff from './Stuff'

export default Stuff
```
2. Have the organizer do its thing
3. Behold!

**Comment by cspotcode** [comment]
Here is another reproduction of this bug.  The `Kept` imports are retained but the `Removed` imports are removed by "organize imports."  It seems like the subscripting operator doesn't count the left-hand-side as being used.

```typescript
import { a as aKept1 } from './other';
import { a as aKept2 } from './other';
import { a as aKept3 } from './other';
import { a as aKept4 } from './other';
import { a as aRemoved1 } from './other';
import { a as aRemoved2 } from './other';

const thisVariableExists = 'foo';

aKept1.thisPropertyDoesNotExist;
alert(aKept2.thisPropertyDoesNotExist);
thisFunctionDoesNotExist(aKept3);
aKept4['thisFieldExists'];

aRemoved1[thisVariableExists];
aRemoved2[thisVariableDoesNotExist];
```

```typescript
// other.ts
export const a = {
    foo: true,
    thisFieldExists: true
};
```

**Comment by buehler** [comment]
Well then they are not recognized as "usage" by the parser :-) I'll need to fix that in 
https://github.com/buehler/node-typescript-parser

And I saw: thank you for opening an issue there :-)
(https://github.com/buehler/node-typescript-parser/issues/32)

**Comment by gianmarcotoso** [comment]
I just saw the reply! Thanks for looking into this. Since the issue is elsewhere, should we close this one?

**Comment by buehler** [comment]
I'm not sure if it's the same issue. Honestly, since I wrote the parser, there could be more that is missing ;-)
