### ISSUE TITLE
indent shortcut overridden by default

### ISSUE THREAD

**Issue by phra** [buehler/typescript-hero#324]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: debian sid
- TypeScript Hero version: latest
- VSCode version: latest

#### Description
the default shortcut to indent code on linux with vscode is being overriden by this plugin.
imho all the plugins should not change the common behavior of the editor until explicitly requested.

##### Steps to reproduce

1. install the extension
2. try to indent the code with the default shortcut on linux (`ctrl + shift + i`)
3. addImport menu opens
4. no ways to indent the code from keyboard anymore

**Comment by buehler** [comment]
I really didn't know that on windows it's this shortcut. But you could actually just overwrite the keybindings. So maybe they changed some keybindings again in vscode, because when I originally added my keyboard shortcuts, this one wasn't taken.
