### ISSUE TITLE
Settings resolver.multiLineWrapThreshold has no effect

### ISSUE THREAD

**Issue by mpicard** [buehler/typescript-hero#333]
#### System information

- OS: Linux 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- TypeScript Hero version:  1.7.0
- VSCode version: 1.17.2

#### Description
setting "typescriptHero.resolver.multiLineWrapThreshold" has no effect on import line wrapping, setting to any number and formatting always results in single line import statement despite length exceeding setting number value.

##### Steps to reproduce

1. change setting "typescriptHero.resolver.multiLineWrapThreshold" to given numerical value 
2. write an import statement that exceeds the given value
3. format document, notice line has not been formatted to the multi line import style and remains single line

**Comment by Hainesy** [comment]
Did you try restarting VS Code after changing the setting?

I've just tested and it works for me on Windows 10, VS Code 1.18.0 and TS Hero 1.7

**Comment by mpicard** [comment]
Restarting fixed it. Sorry I forgot I opened this
