### ISSUE TITLE
Question: shouldn't regex import groups take precedence over group keywords?

### ISSUE THREAD

**Issue by tdd** [buehler/typescript-hero#334]
Hey team, thanks a ton for the awesome import magic in here! An issue tho…

#### System information

- OS: OSX El Capitan
- TypeScript Hero version: 1.7.0
- VSCode version: 1.17.2

#### Description

I’ve got the following configuration set up:

```js
{
  // …
  "typescriptHero.resolver.importGroups": [
    "Modules",
    "/material-ui/",
    "Plains",
    "Workspace"
  ]
}
```

The idea is that I'd like my npm-installed imports from material-ui to be in their own groups, below regular modules and plains, and before my workspace files. Say, I should get the following:

```js
import autobind from 'autobind-decorator'
import PropTypes from 'prop-types'
import React, { Component } from 'react'
import DocumentTitle from 'react-document-title'
import { connect } from 'react-redux'

import { Card, CardActions, CardText, CardTitle } from 'material-ui/Card'
import RaisedButton from 'material-ui/RaisedButton'
import Snackbar from 'material-ui/Snackbar'
import ArrowForward from 'material-ui/svg-icons/navigation/arrow-forward'
import TextField from 'material-ui/TextField'

import '../styles/LoginScreen.styl'

import { LoginStatePropType } from '../prop-types'
import { logIn } from '../reducers/currentUser'
```

However, material-ui imports get lumped in with the Modules group: their group definition is entirely ignored. Like this:

```js
import autobind from 'autobind-decorator'
import { Card, CardActions, CardText, CardTitle } from 'material-ui/Card'
import RaisedButton from 'material-ui/RaisedButton'
import Snackbar from 'material-ui/Snackbar'
import ArrowForward from 'material-ui/svg-icons/navigation/arrow-forward'
import TextField from 'material-ui/TextField'
import PropTypes from 'prop-types'
import React, { Component } from 'react'
import DocumentTitle from 'react-document-title'
import { connect } from 'react-redux'

import '../styles/LoginScreen.styl'

import { LoginStatePropType } from '../prop-types'
import { logIn } from '../reducers/currentUser'
```

Is that as intended?

##### Steps to reproduce

1. Create a workspace
2. Plug the related config fragment in your workspace settings
3. Create a file with the last import list
4. Save (and if not auto-organizing, organize)

Best,

**Comment by tdd** [comment]
BTW it seems to me the culprit is at https://github.com/buehler/typescript-hero/blob/develop/src/extension/managers/ImportManager.ts#L411-L419

As you can see, whatever first group def matches gets the prize. There's no prioritization of non-keyword groups over keywords. It seems to me keywords should have lower precedence than explicit groups, don't you think?

**Comment by buehler** [comment]
Actually @tdd, that's a good idea :-)
I'm trying to improve the import grouping logic further. Because right now, even I'm not as happy as I should be with it. Maybe there should be some other logic for it.

If you have any input on (not only about priorities) how to implement a grouping system, it would be appreciated.
