### ISSUE TITLE
How to use typescripthero commands?

### ISSUE THREAD

**Issue by akshaykhanna** [buehler/typescript-hero#343]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: <operating system>
- TypeScript Hero version: <version>
- VSCode version: <version>

#### Description

<what is going wrong>

##### Steps to reproduce

1. Do
2. That

<for feature requests, please use the following template>

#### Feature <name>

<description>

#### Reason

<why it would be cool>

**Comment by buehler** [comment]
You can bind commands to keys in the keybindings.json of vscode. Or you can use `cmd shift P` to open the command palette.
