### ISSUE TITLE
Cannot see imported module usage so deletes on save

### ISSUE THREAD

**Issue by lukevenn** [buehler/typescript-hero#346]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: MacOS
- TypeScript Hero version: 1.7.0
- VSCode version: 1.18.0

#### Description

We have an import that is passed as an object property inside a react component property like:
```
<Message
  tagsMap={{
    b: Bold,
  }}
  id="messageId"
/>
```
When we save using `organiseOnSave` either via keyboard shortcut or settings it removes the import. If we add a usage in JSX like `<Bold />` then the import is not removed which is what leads me to believe that it is due to the fact that typescript-hero cannot see the usage described above.

##### Steps to reproduce

1. With the `typescriptHero.resolver.organizeOnSave` setting set to `true`
2. import a React component (or any module I assume although not tested this)
3. Reference it in the above way inside a react component
4. Save the file
5. The imported module is removed

**Comment by buehler** [comment]
This should be fixed by #360 
Feel free to reopen the issue
