### ISSUE TITLE
Organize imports removes used imports

### ISSUE THREAD

**Issue by deniaz** [buehler/typescript-hero#352]
#### System information

- OS: macOS Sierra
- TypeScript Hero version: 1.7.0
- VSCode version: 1.18.1

#### Description

In some scenarios the `TS Hero: Organize imports (sort and remove unused)` command removes imports eventhough the _are_ being used. So far I couldn't figure out when/why this happens. As discussed with you, I'm creating this issue to track occurance of this happening so we can hopefully figure it out.

It _could_ be happening with JSX/TSX - but that's just a wild guess.

##### Steps to reproduce

1. Take one of the code snippets from the comments below.
2. `TS Hero: Organize imports (sort and remove unused)` (or `^` `⌥` `O`)

**Comment by deniaz** [comment]
```typescript
import * as React from 'react';
import { t } from 'i18next';

export const MyComponent = () => (
  <p>{t('foo')}</p>
);
```

`import { t } from 'i18next';` gets removed.

**Comment by mircostraessle** [comment]
+1

**Comment by deniaz** [comment]
Okay, another one which supports the TSX-theory, but not the destruct-statement from above:

*helper.ts*:
```typescript
export const getActiveLanguage = () => { /* ... */ };

export const getActiveTheme = () => { /* ... */ };
```

*app.ts*:
```typescript
import * as React from 'React';
import { getActiveLanguage, getActiveTheme } from './helper';

const App = /* React TSX */;
ReactDOM.render(
  <App theme={getActiveTheme()} lang={getActiveLanguage()} />, 
  document.getElementById('root')
);
```

Organising my imports _removes_ `getActiveTheme` and `getActiveLanguage`.

**Comment by deniaz** [comment]
jest test:
```typescript
// utils/helper.ts

const themes = {
 // ...
};

export const getThemeByKey = (name: string) => Partial<Theme> => themes[name] ? themes[name] : themes['default'];

```

```typescript
// test.tsx
import * as React from 'react';
import { create } from 'react-test-renderer';
import { ThemeProvider } from 'styled-components';

import { getThemeByKey } from './utils/theme';

it('renders', () => {
  const component = create(
    <ThemeProvider theme={getThemeByKey(DEFAULT_THEME)}>
      <PageTitle>Ein Titel</PageTitle>
      </ThemeProvider>,
  ).toJSON();
  expect(component).toMatchSnapshot();
});
```

Organising imports removes `getThemeByKey`.

**Comment by Zephir77167** [comment]
+1, happens often with named AND default exports

**Comment by deniaz** [comment]
Held
