### ISSUE TITLE
Saving file with TypeScript Hero enabled freezes vim extension

### ISSUE THREAD

**Issue by lionize** [buehler/typescript-hero#353]
#### System information

- OS: 10.13.1
- TypeScript Hero version: 1.7.0
- VSCode version: 1.18.1

#### Description

When the official Vim extension and TypeScript Hero extension are enabled, saving a file causes the Vim extension to stop responding for 2-4 seconds. After that time, all of the entered keystrokes will be executed, like they had been queued up during that time.

Unsure if this is necessarily a TypeScript Hero problem, but I have disabled all extensions and enabled them one at a time and only TypeScript Hero causes this freezing problem with vim.

##### Steps to reproduce

1. Install TypeScript Hero.
2. Install Vim extension.
3. Edit a TypeScript file and save it.
4. Attempt to enter keystrokes. They will work for a second after saving but then will freeze for a few seconds.

**Comment by nhance** [comment]
It appears that the vim input is paused when typescript here runs the DeclarationIndexMapper.

Running the debug console I was able to pin down the freezes to happen over the 8.545 seconds between these lines in console:

```
[Extension Host] 2017-12-21T19:17:24.485Z - debug: [DeclarationIndexMapper] rebuilding index for index "c:\Users\nick\Source\Repos\****-mobile"

[Extension Host] 2017-12-21T19:17:33.030Z - info: [DeclarationIndexMapper] rebuilt index for workspace "***-mobile" {"durationMs":8545}
```

**Comment by obeyda** [comment]
I still have exactly the same issue.

System information
    OS: Arch linux
    TypeScript Hero version: 2.1.1
    VSCode Version: 1.19.3

**Comment by jiajerry** [comment]
Still having the same issue as well
Any updates on this?

Vim Version: 0.13.0
TypeScript Hero Version: 2.3.2
VSCode Version: 1.24.1
