### ISSUE TITLE
Multiline imports should respect indentation settings

### ISSUE THREAD

**Issue by Springrbua** [buehler/typescript-hero#361]
Related: #74 

#### System information

- OS: Windows 10 x64
- TypeScript Hero version: 1.7.0
- VSCode version: 1.18.1

#### Description

When using the `organize-imports`-command, long imports might be converted to multiline imports.  
However, the multiline imports always use `spaces` as indentation, even if it is set to `tabs`.

##### Steps to reproduce

1. Set indentation to tabs in a `TypeScript`-File
2. Create a long `import`-statement.
3. Use `organize-imports`-command

The multiline import now uses `spaces` instead of `tabs`, the indentation size seems to be respected.

**Comment by blahDL** [comment]
It would be greatly appreciated if this extension observed the configuration options `editor.detectIndentation` and `editor.insertSpaces` and inserted tabs or spaces depending on what is configured.

**Comment by Springrbua** [comment]
@buehler Thanks for your afford. Is there any setting to use tabs instead of spaces? In my case it is still using spaces in multiline imports, even if the file is set to tabs.
