### ISSUE TITLE
Ctrl + Shift + I Crashes the extension (Add Import)

### ISSUE THREAD

**Issue by anttikeinonen** [buehler/typescript-hero#362]
#### System information

- OS: Windows 10 64bit
- TypeScript Hero version: 1.8.0 (2017-12-11)
- VSCode version: 1.18.1

#### Description

Ctrl + Shift + I Crashes the extension (Add Import)

##### Steps to reproduce

1. Install extension
2. Reload
3. Ctrl + Shift + I 
4. Wait few seconds
5. Crash

**Comment by Dahaden** [comment]
Same issue, 
OS: Mac 10.12.6
Same versions otherwise

**Comment by anttikeinonen** [comment]
Typescript Hero version now 1.8.0 (2017-12-11) and it still happens.

**Comment by buehler** [comment]
Duplicate #363
