### ISSUE TITLE
Recent update broke autocompletion

### ISSUE THREAD

**Issue by kmathy** [buehler/typescript-hero#365]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: Windows 10
- TypeScript Hero version: 1.8
- VSCode version: 1.19

#### Description

Few days ago, the plugin worked perfectly. But with the recent update, autocompletion completely disappeared during typing. I can't automatically import a component or a service in Angular. 

Moreover, I looked inside the log file and it seems OK, no error, only 

> 2017-12-16T15:34:30.049Z - info: [DeclarationIndexMapper] rebuilding all indices
> 2017-12-16T15:34:38.966Z - info: [DeclarationIndexMapper] built index for workspace "project" {"durationMs":8915}

##### Steps to reproduce

1. type the component name
2. No suggestion provided

**Comment by subvertallchris** [comment]
Came here to report the same thing.

**Comment by subvertallchris** [comment]
Sorry to be a pain, any word on this?

**Comment by idchlife** [comment]
same here

**Comment by buehler** [comment]
Hey guys, I experienced the same stuff lately and I'm trying to fix it asap.

**Comment by subvertallchris** [comment]
Can you publish the 1.7.0 vsix somewhere? I'd like to downgrade in the meantime.

**Comment by Crazybutch** [comment]
https://tpodolak.com/blog/2017/04/09/downgrading-visual-studio-code-extension/

https://rbbit.gallery.vsassets.io/_apis/public/gallery/publisher/rbbit/extension/typescript-hero/1.7.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
