### ISSUE TITLE
Ctrl+Alt+i show long list of paths

### ISSUE THREAD

**Issue by johne2310** [buehler/typescript-hero#37]
Previous version (0.54) showed short (local?) list of import files. Updating to 0.60 show infinite list of files. See attached pic.
![vscode typescript hero 2](https://cloud.githubusercontent.com/assets/12781989/18405110/915bf2de-7732-11e6-9d04-285babfb0f66.png)

**Comment by buehler** [comment]
Holy...
Well. This has something to do with the 1.5.1 update. They changed some stuff with the workspace path engine.
I'll have a look into it.

**Comment by buehler** [comment]
In addition: if you simply want to exclude `compiler` for example, you can do so with the exclude path setting of the resolver.

**Comment by buehler** [comment]
@johne2310 alright, I analyzed the behaviour. All those keys are exported variables by angular. What I actually can do is sort the own workspace files to the top, but the list won't be any shorter. But at least, your own files are at the top.

What do you think?

**Comment by johne2310** [comment]
Sounds like a practical solution. Many thanks.
