### ISSUE TITLE
extension made vscode unusable (keyboard not responding at all)

### ISSUE THREAD

**Issue by olivoil** [buehler/typescript-hero#372]
#### System information

- OS: linux (ubuntu 17.10)
- TypeScript Hero version: 1.8.0
- VSCode version: 1.19.1

#### Description

Vscode started not responding to any keyboard input while editing a .ts file. I disabled all extensions, reloaded, and it worked again. Proceeded to enable all extensions again, and disable them one by one until I found the culprit. Disabling typescript hero fixed the issue.

I'm not sure how to reproduce exactly, or what specifically in my project or environment makes the extension behave this way... I'm editing a project bundled by parceljs, and don't have a tsconfig.json in the project. Feel free to ask any question that will help figure it out.

**Comment by maplion** [comment]
With the 1.19.1 VSCode update, for us, Typescript Hero was found to be the culprit in causing the VSCode Extension Host to crash, rendering all extensions useless.  As above, extensions were disabled one at a time until it was found that Typescript Hero was causing the issue.

**Comment by BenjaminAbt** [comment]
Same issue for
* Windows 10.0.16299.192
* TypeScript Hero 1.8.0

- VSCode Version 1.19.2
- Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
- Date 2018-01-10T15:55:03.538Z
- Shell 1.7.9
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64

**Comment by stevenmusumeche** [comment]
Same here.
