### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by mpicard** [buehler/typescript-hero#376]
#### Feature changelog

add a changelog for each version, even if it's minimal

#### Reason

would be great to know what's new, what's changed, what's fixed

**Comment by buehler** [comment]
Hey @mpicard 
I actually had that. But right now, it's not possible :-)

There is a changelog though: https://github.com/buehler/typescript-hero/releases
There you have the versions with documented changes.

There will be a changelog again in the future, but I don't know when I got time to implement it.

**Comment by mpicard** [comment]
Oh sorry I must have missed the releases page, sorry! That's good enough for me

**Comment by buehler** [comment]
No worries :-)
