### ISSUE TITLE
Import symbol under cursor removed?

### ISSUE THREAD

**Issue by froodley** [buehler/typescript-hero#382]
What happened to the option to import symbol under cursor?  I was using this constantly.

**Comment by buehler** [comment]
Hey @froodley 
https://github.com/buehler/typescript-hero/releases/tag/v2.0.0
This should answer your question.

Sadly, some parts of the feature did actually _kill_ vscode for quite some people. I did remove it to "fix" this problem. And I'm working on it to bring it back asap. But I need to refactor some things.

**Comment by buehler** [comment]
https://github.com/buehler/typescript-hero/pull/383

It's back 😄

**Comment by buehler** [comment]
But I needed to refactor some parts of the application. I determined the errors. Kinda.

**Comment by froodley** [comment]
Oh, outstanding, I'll try it out
