### ISSUE TITLE
VS Code Output panel opens to TypeScript Hero on launch

### ISSUE THREAD

**Issue by subvertallchris** [buehler/typescript-hero#390]
#### System information

- OS: Mac OS 10.12.6
- TypeScript Hero version: 2.1.1
- VSCode version: 1.19.3

#### Description

When I open VS Code, it opens the Output panel and selects TypeScript Hero. Does not matter whether I have the entire bottom panel open or closed, it always goes to TS Hero.
 
##### Steps to reproduce

1. Close the Output panel in VS Code
2. Quit out of VS Code
3. Open VS Code and wait a few seconds

It's certainly not the end of the world but I keep forgetting to switch back to my Problems panel

**Comment by buehler** [comment]
Yea that's the logger :-)
I'll have a look at it.

**Comment by TheSpyder** [comment]
Pretty sure it's your call to `show` - documentation says this reveals the channel in the UI ;)
https://github.com/buehler/typescript-hero/blob/develop/src/utilities/logger.ts#L78

I'd make a PR but I'm not really in a position to verify the fix at the moment 🤔
