### ISSUE TITLE
Gitter communities for `typescript-hero` and `node-typescript-parser`

### ISSUE THREAD

**Issue by shobhitg** [buehler/typescript-hero#393]
Not sure if you are a gitter.im user.

Most of the important github projects (vscode/rxjs/redux/ngrx/react) do have a good community presence on gitter. Sometimes it is easier to ask small clarifications, or coordinate on gitter chat rather than creating github issues. I highly recommend that you create gitter spaces for both `typescript-hero` and `node-typescript-parser`.

@buehler Since both of these projects are your repositories, therefore only you can create gitter communities for them.
Goto: https://gitter.im
Sign-in/Authenticate yourself via GitHub so that Gitter knows about your github repositories.
Then goto: https://gitter.im/home/explore#createcommunity

Look for `do you want to start a community for one of your github projects?`
And I am sure you can navigate yourself from there.

Thanks.

**Comment by buehler** [comment]
Will do :-)

**Comment by shobhitg** [comment]
Hi, I saw the community you created.

It doesn't look right.
It seems you created a room that isn't connected to your repo `buehler/typescript-hero`.
When you reached [this gitter site](https://gitter.im/home/explore#createcommunity), did you create the community using the link provided in the text `do you want to start a community for one of your github projects?`

![screenshot 2018-02-05 10 39 09](https://user-images.githubusercontent.com/440151/35822533-7687098a-0a61-11e8-837f-d587bc18519d.png)

**Comment by buehler** [comment]
Hmm I actually did... let me try that again.

**Comment by buehler** [comment]
Alright.
The communities are opened. I'll add the badges right away.

https://gitter.im/vscode-typescript-hero/
and
https://gitter.im/node-typescript-parser
