### ISSUE TITLE
Typescript Hero remove useful import

### ISSUE THREAD

**Issue by YihaoJiang** [buehler/typescript-hero#394]
#### System information

- OS: Windows 10
- TypeScript Hero version: 2.1.1
- VSCode version: 1.19.3

#### Description

It removes useful import.

##### Steps to reproduce

Type these code in one file in vscode.

`import Test from './Test';`
`export default Test;`

Try to save the file, and Typescript Hero will remove this import.

**Comment by shobhitg** [comment]
@buehler This seems to be happening due to this line:
https://github.com/buehler/node-typescript-parser/blob/a6556108d291fcbadbf1d7f964be062f776028e2/src/resources/File.ts#L34

I am not clear why are we filtering away `declarations` from `nonLocalUsages` ?

**Comment by theigor** [comment]
This seems the same as https://github.com/buehler/typescript-hero/issues/380. Just encountered this today.

**Comment by buehler** [comment]
Duplicate #380
