### ISSUE TITLE
Config in file

### ISSUE THREAD

**Issue by ruimserrano** [buehler/typescript-hero#408]
#### Feature <name>
config in a file
<description>

Just like prettier, i would like to have ts-hero configuration load by an external file.
could have a .tsherorc, then fallback to .editorconfig, then fallback to vscode settigns.
#### Reason
The motivation is that we can have different settings by project since the config file can be pushed with the rest of the files.
Another motivation is the team mates can have ts-hero automatically configured.

Usually when a new guy commits code, i notice that the imports are not sorted nicely. So i have always to send my settings to the new guy...

**Comment by shobhitg** [comment]
In vscode, you could create a workspace. And have all the tshero settings in workspace settings file (which would be tracked by git).

**Comment by buehler** [comment]
Actually yea.. :-)
Never saw an extension that did that. The natural way to config an extension is via settings.json or workspace settings.json.
