### ISSUE TITLE
Configurable space where imports are written

### ISSUE THREAD

**Issue by buehler** [buehler/typescript-hero#41]
Related from #22

It should be possible to configure, where new imports are inserted

I can think of 2 possibilities:
- At the top of the document (default)
- At the current cursor position; *IF* there is already some text in the currently selected line, the line above will be used

**Comment by fxck** [comment]
lgtm

**Comment by buehler** [comment]
@fxck Just to notify you, the next version will contain this feature ;-)

**Comment by fxck** [comment]
Cool, what's the ETA? :)

**Comment by buehler** [comment]
Phew, good question :-) as soon the milestone 0.8 is done 
possibly in the next few days

**Comment by fxck** [comment]
You sure you didn't mean next few hours lol. Good job.

**Comment by buehler** [comment]
Whoops :-) got some time and it wasn't that much of a challenge.. (as you see in the PR)

**Comment by buehler** [comment]
@fxck Alright.. the new version is deployed :-)

**Comment by fxck** [comment]
@buehler works fine, but it's still reoganizing my existing imports, changing indentation and stuff :(

before

```typescript
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy
} from '@angular/core';
import {
  FormControl,
  FormGroup,
  Validators
} from '@angular/forms';

```

after 

```typescript
import {
    ChangeDetectionStrategy,
    Component,
    EventEmitter,
    Input,
    Output
} from '@angular/core';
import {
    FormControl,
    FormGroup,
    Validators
} from '@angular/forms';

```

**Comment by buehler** [comment]
Oh bummer...
Do you configure the spaces in your vscode file? So it would be an option to get the configured value out of the vscode config to add the spaces or tabs?

Cheers

**Comment by fxck** [comment]
Well first of all, it should completely ignore existing imports, no A-Z reordering, no touching of indentation. But yeah, when it comes to indentation of typescript-hero's imports, it should use current indentation of the editor, but AFAIK I don't have it explicitly set, but it's reading it automatically from the file. I'll check tomorrow.

**Comment by fxck** [comment]
Ok, so I do have 

```
"editor.tabSize": 2
```

in my user settings

**Comment by buehler** [comment]
Ok I need to check the code for that :-)
It actually wasn't the idea to touch every import but maybe for some reason I did exactly that. I'll have a look at that. But I'll move it to another ticket, since it's a feature on its own.
