### ISSUE TITLE
Organize imports remove imports used in export statements

### ISSUE THREAD

**Issue by tonyxiao** [buehler/typescript-hero#411]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: MacOS 10.13.3
- TypeScript Hero version: 2.2.0
- VSCode version: 1.20.1

#### Description

Organize imports remove imports used in export statements

##### Steps to reproduce

Before organize imports
![image](https://user-images.githubusercontent.com/696842/36745841-ff4bcd66-1bad-11e8-905f-31fa2eb91590.png)

After organize imports
![image](https://user-images.githubusercontent.com/696842/36745859-10d462aa-1bae-11e8-9cb5-956ba7b7d9a8.png)

**Comment by shobhitg** [comment]
Looks like related to #394.

**Comment by tonyxiao** [comment]
Oh looks right - should we close as duplicate?

**Comment by buehler** [comment]
Related to #380
