### ISSUE TITLE
Do not move schebang

### ISSUE THREAD

**Issue by rlz** [buehler/typescript-hero#412]
Typescript Hero moves schebang comment after imports. If you have a file like

1. #! /usr/bin/env node
2.
3. import ...
4. 

It will become:

1. import ...
2.
3. #! /usr/bin/env node
4.

Which is wrong. If the first line starts with "#!" it must not touch it.

**Comment by rlz** [comment]
When are you going to release?

**Comment by buehler** [comment]
This should be released. https://github.com/buehler/typescript-hero/releases/tag/v2.3.0
v.2.3.1
