### ISSUE TITLE
Not working in tsx files

### ISSUE THREAD

**Issue by Ciantic** [buehler/typescript-hero#42]
I have fairly big react app, and I'm not sure is it this app only, or tsx files, but Ctrl+Alt+I says "There are no entries to pick from", typing there gives empty also. 

However e.g. VS Code's own "Ctrl+T" symbol explorer finds all components and functions just nicely.

Does this extension have some sort of own resolver? I can see the "Resolver checkmark" in the status bar, maybe it doesn't work with TSX files? 

If there is some own file indexer, I don't understand why, surely the VSCode already has index of all symbols and their paths since this can show them:

![image](https://cloud.githubusercontent.com/assets/64731/18434892/a696e948-78f8-11e6-9e36-451393c04039.png)

I'd imagine calculating the relative path to the given file in symbols view should give the same import path?

Thanks.

**Comment by buehler** [comment]
Hi @Ciantic 
Sadly, there is no file indexer exposed to extension developers. So I did it myself with the help of the typescript compiler. But ye, tsx files are not indexed yet.

Good point, and I'll definitely look into it.

Cheers

**Comment by Ciantic** [comment]
I opened an issue to vscode, surely there must be some better way than to re-implement file-indexer. See issue https://github.com/Microsoft/vscode/issues/11949

**Comment by buehler** [comment]
@Ciantic thanks mate :smile:

Let's see what they mean. Actually, just to add `*.tsx` files, shouldn't be much work, but yea if this would be offered by vscode would be nice ;-)

Cheers

**Comment by buehler** [comment]
@Ciantic would you mind to write a small `tsx` example here?
A small bit of code, so I can test it against the extension.

**Comment by Ciantic** [comment]
the simplest stateless component is just exported function, like this:

```
import * as React from "react"; // I think this is not even required for JSX to be valid for TypeScript
export const myComponent = (test: string) => {
    return <div>Hello World: {test}</div>
}
```

**Comment by buehler** [comment]
Alright, this looks like "normal" typescript, so it shouldn't be a problem to throw this file at the typescript compiler.

**Comment by buehler** [comment]
@Ciantic could those tsx files also be in a node module or a typings lib?

**Comment by buehler** [comment]
Well I solved the question ;-)
Next version will have tsx support.
