### ISSUE TITLE
Generates `Duplicate Identifier` for already imported stuff via multiline import

### ISSUE THREAD

**Issue by dwirz** [buehler/typescript-hero#43]

**Comment by buehler** [comment]
General problem with multiline imports :-)

**Comment by kkovalevskiy** [comment]
Multiline imports are required for cases when tslint "max-line-length" rule is enabled (I think that the most of ts projects are using this rule), so the issue is pretty actual

**Comment by buehler** [comment]
Whoops. Well I planned to fix "all" the bugs first (in this issue list) before implementing new features, so it'll be in the next release(ses)
