### ISSUE TITLE
Command '...' not found

### ISSUE THREAD

**Issue by varHarrie** [buehler/typescript-hero#436]
#### System information

- OS: Win 10
- TypeScript Hero version: 2.3.2
- VSCode version: 1.22

#### Description

```
command 'typescriptHero.imports.organize' not found

command 'typescriptHero.index.addImport' not found
```

##### Steps to reproduce

1. Upgrade TS Hero (latest) and VSCode (>= 1.2).
2. Execute commands with 'CTRL+SHIFT+P', or use shortcut keys, then show error.
3. I have tried to reinstall TS Hero and didn't work.

**Comment by abhisekbit** [comment]
Same issue...any solution ?

**Comment by matiascuestas** [comment]
Same issue :S

**Comment by varHarrie** [comment]
More exactly:
1. Delete the folder `%USERPROFILE%/.vscode/rbbit.typescript-hero-2.3.2`.
2. Install `typescript-hero` again.
