### ISSUE TITLE
Node modules typings support

### ISSUE THREAD

**Issue by MastroLindus** [buehler/typescript-hero#63]
Be able to import symbols from node projects, ideally supporting both styles in here https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html  and the new typescript 2 "@types" syntax.

**Comment by buehler** [comment]
Actually, `*.d.ts` files, that are contained in node_modules are indexed as well.
Or what do you mean exactly?

The @types will be supported, when typescript 2 is officially out ;-) Right now, the extensions do not run on typescript 2, so you cannot parse those new notations.

**Comment by buehler** [comment]
Referenced in #77
