### ISSUE TITLE
Multiline imports must respect indentation settings

### ISSUE THREAD

**Issue by buehler** [buehler/typescript-hero#74]
Comes from #41 

- Respect the editors settings for indentation
- Refactor importing logic, do not touch existing imports

**Comment by Springrbua** [comment]
@buehler I know this Issue has been closed over a year ago, but it does not seem to work (anymore?).  
I am using tabs for indentation (size = 4) and when I use the `organize imports`-command, it converts the intendation in multiline-imports to spaces.  
Am I just missing some settings?

**Comment by buehler** [comment]
@Springrbua actually... I think it only uses spaces.
I need to review that.

Could you make an issue with a feature request to actually use tabs when configured as such?

**Comment by Springrbua** [comment]
@buehler thanks, I've created #361 :)
