### ISSUE TITLE
Remove the need to restart VS Code when typescriptHero.resolver.ignorePatterns setting is changed.

### ISSUE THREAD

**Issue by SetTrend** [buehler/typescript-hero#75]
Using the `typescriptHero.resolver.ignorePatterns` option is a bit cumbersome because VS Code needs to be restarted for accepting the changes.

Please add a watcher to settings so their values are getting caught immediately when saving the `settings.json` file.

**Comment by buehler** [comment]
Actually, there is an event for that. Good point! Thanks

**Comment by SetTrend** [comment]
Excellent! Thanks :+1: :cake:
