### ISSUE TITLE
Respect usual semantic import groups

### ISSUE THREAD

**Issue by DiamondeX** [buehler/typescript-hero#82]
This is an offspring proposal of #73 in part of 5th option: _Ability to use three common groups of imports delineated by blank lines: provided by node (fs, path, http etc.), provided by npm (express, angular, chalk etc.) and project specific (defined with path)_

I suggest following logic to distinguish groups.
1. There are limited number of Node built-in modules. So, first of all we may check imports with such list.
2. Left modules we may differentiate by leading dot. Those without leading dot are npm modules.
3. All others are in the last group.

The last group optionally we may divide on subgroups starting with those from outer dirs (multiple leading `../`), then from subdirs of outer dirs (with leading `../../dir/dir/file[.ext]`), then from inner dirs (`./dir/file[.ext]`) and at last neighbours (`./file[.ext]`). Nevertheless even alphabetical sorting may be enough for good code style

I named this semantic groups "usual" because I saw such groupping very often and in a lot of large, well-known projects, i.e. see code examples at this [page about using webpack with angular 2](https://angular.io/docs/ts/latest/guide/webpack.html)

**Comment by buehler** [comment]
I'll take it into account.. but I really do like to implement some other stuff first ;-)

**Comment by michaeljota** [comment]
I came here to ask if we could set the position of the import line to the bottom of the import list, but this is really what I was looking after. 

BTW, great tool. Idk how I coded without it.

**Comment by buehler** [comment]
@michaeljota Thanks :-)
I assume this should be a more or less easy change. I'll open a separate ticket for that matter since this one is more complicated.

**Comment by buehler** [comment]
This issue is being tracked in #97 and #102
