### ISSUE TITLE
Organize imports: Reference path gets moved below imports and fails

### ISSUE THREAD

**Issue by jamesgroat** [buehler/typescript-hero#83]
I have a reference path defined that gets moved to below the import tags and hence fails. Reference paths should apparently be kept at the top?

i.e. 
```
/// <reference path=".../blah.d.ts" />
import { Whatever } from 'blah';
```

**Comment by buehler** [comment]
Hey @jamesgroat 
Oh.. those are still used? 

I thought with typings / @types references, those reference paths were a thing of the past.

I'll have a look at it

**Comment by jamesgroat** [comment]
I'm using one as a hack b/c rollup.js is not playing nice with a 3rd party library. Either way, would be nice to have it not re-order the lines in a way that breaks the reference.

Thanks!

**Comment by buehler** [comment]
Well.. bad news :-(
I investigated the problem and analyzed the generation of the AST by the compiler. Sadly, there are no tokens generated for reference pathes.

This is the source:
```typescript
/// <reference path="../foo.bar.d.ts" />

```

The generated AST looks like this:
```bash
 SourceFile 0 41
---- SyntaxList 0 0
---- EndOfFileToken 0 41
```

My suggestion would be:
```typescript
const bla = require('bla');
```

If the library is enriched with JSDocs, vscode will parse those and give you intellisense. But sadly, typescript does not provide any information for those references anymore.

Cheers

**Comment by jamesgroat** [comment]
@buehler any chance we can just treat it like a special-case comment and leave those at the top of the page when organizing imports?  Thanks either way for having looked.
