### ISSUE TITLE
Auto import for `console`?!

### ISSUE THREAD

**Issue by cebor** [buehler/typescript-hero#99]
When typing `console` ts-hero automatically adds the following import statement

``` typescript
import * as console from 'console';
```

This produces an error.

**Comment by buehler** [comment]
Oh ... :-) seems like globals must be handled specally..

**Comment by buehler** [comment]
Actually, I saw that there is a namespace "console" and a declared var named console. Since the sort order of vscode lists the namespace first, you get the import.

Maybe I can implement a custom sort to order namespaces and modules to the bottom.

**Comment by buehler** [comment]
I just tested it, and the console from the `VariableDeclaration` is hit everytime when I write `console`. Maybe they changed something in the sorting logic. But right now, I'm not experiencing this strange behaviour anymore.

I'll do a release without anything to this, if it still persists to be an error, feel free to write here and I'll reopen it and investigate the error.

**Comment by cebor** [comment]
Problem still exists for me ...

**Comment by buehler** [comment]
@cebor 
Hmm this behaviour is strange.. when I type `console` the autocompletion looks like this:
![completion](https://dl.dropboxusercontent.com/spa/agn3r6rkwi4rxn7/1ii-5s5e.png)
and when I hit enter or tab or whatever, it does not import anything.

**Comment by rosslavery** [comment]
This also happens for me from time to time. Not always, but it's hard for me to track down when it happens and when it doesn't.

**Comment by buehler** [comment]
Hmm.. well then I try to use this sort property to rule down the namespace.
If I give you a branch with the implementation, would some of you mind to test it with a build from an experimental branch? So I do not need to release a version with the possible bugfix and maybe it's still not fixed.

**Comment by cebor** [comment]
@buehler yes, i will test it when you release a branch with a possible fix

**Comment by buehler** [comment]
hey @cebor 
I pushed a branch https://github.com/buehler/typescript-hero/tree/fix/console-auto-import.
Could you try it out if the problem still exists?

What I basically do is to sort variables before all other things. So by default, if a variable with the given name exists, it should be preselected instead of a namespace.

(console namespace declared in node.d.ts and console variable)

**Comment by buehler** [comment]
As a side note: I'm doing a release with the newest feature (implement interface / abstract class), so this is gonna be in a bugfix release if it's resolved.

**Comment by cebor** [comment]
@buehler seems to be fixed in the latest version, dont had time to test the branch.

**Comment by buehler** [comment]
@cebor Alright, I'll merge the branch anyway, since I'm working on a angular2 project right now, I'd experience it as well..
